import { lazy, type LazyExoticComponent, type ComponentType } from "react";

export type FeatureCategory = "Games" | "Player" | "Productivity";

export interface FeatureDef {
  id: string;
  title: string;
  category: FeatureCategory;
  description: string;
  width?: number;
  height?: number;
  loader: () => Promise<{ default: ComponentType }>;
}

export const FEATURES: FeatureDef[] = [
  // Games — originals
  { id: "dino", title: "Dino Runner", category: "Games", description: "Chrome offline dino — Space to jump", width: 640, loader: () => import("./dino") },
  { id: "snake", title: "Snake Classic", category: "Games", description: "Arrow keys / WASD", width: 460, loader: () => import("./snake") },
  { id: "2048", title: "2048", category: "Games", description: "Combine tiles to reach 2048", width: 440, loader: () => import("./twenty48") },
  // Games — new 30
  { id: "tetris", title: "Tetris Mini", category: "Games", description: "Arrows + Space drop", width: 280, loader: () => import("./tetris") },
  { id: "pong", title: "Pong vs CPU", category: "Games", description: "Move mouse to control paddle", width: 460, loader: () => import("./pong") },
  { id: "breakout", title: "Breakout", category: "Games", description: "Mouse paddle, clear bricks", width: 460, loader: () => import("./breakout") },
  { id: "flappy", title: "Flappy Bird", category: "Games", description: "Space / click to flap", width: 440, loader: () => import("./flappy") },
  { id: "tictactoe", title: "Tic-Tac-Toe", category: "Games", description: "Beat the CPU", width: 320, loader: () => import("./tictactoe") },
  { id: "connect4", title: "Connect 4", category: "Games", description: "Four in a row vs CPU", width: 420, loader: () => import("./connect4") },
  { id: "minesweeper", title: "Minesweeper", category: "Games", description: "Right-click to flag", width: 380, loader: () => import("./minesweeper") },
  { id: "memory", title: "Memory Match", category: "Games", description: "Find emoji pairs", width: 340, loader: () => import("./memory") },
  { id: "simon", title: "Simon Says", category: "Games", description: "Repeat the colored sequence", width: 340, loader: () => import("./simon") },
  { id: "whackmole", title: "Whack-a-Mole", category: "Games", description: "30-second mole bash", width: 340, loader: () => import("./whackmole") },
  { id: "reaction", title: "Reaction Test", category: "Games", description: "How fast can you click?", width: 360, loader: () => import("./reaction") },
  { id: "typing", title: "Typing Speed", category: "Games", description: "Type the passage — WPM scored", width: 480, loader: () => import("./typing") },
  { id: "clicker", title: "Clicker", category: "Games", description: "Tap to score, upgrade, repeat", width: 320, loader: () => import("./clicker") },
  { id: "rps", title: "Rock Paper Scissors", category: "Games", description: "Best out of many vs CPU", width: 360, loader: () => import("./rps") },
  { id: "coinflip", title: "Coin Flip", category: "Games", description: "Heads or tails", width: 320, loader: () => import("./coinflip") },
  { id: "dice", title: "Dice Roller", category: "Games", description: "1–6 dice, animated", width: 360, loader: () => import("./dice") },
  { id: "numberguess", title: "Guess the Number", category: "Games", description: "1–100, higher/lower hints", width: 360, loader: () => import("./numberguess") },
  { id: "higherlower", title: "Higher or Lower", category: "Games", description: "Card streak game", width: 360, loader: () => import("./higherlower") },
  { id: "hangman", title: "Hangman", category: "Games", description: "Guess the word in 6 misses", width: 420, loader: () => import("./hangman") },
  { id: "anagram", title: "Anagram Solver", category: "Games", description: "Unscramble the word", width: 360, loader: () => import("./anagram") },
  { id: "mathquiz", title: "Math Sprint", category: "Games", description: "60-second arithmetic", width: 380, loader: () => import("./mathquiz") },
  { id: "lightsout", title: "Lights Out", category: "Games", description: "Turn off every light", width: 340, loader: () => import("./lightsout") },
  { id: "fifteen", title: "15-Puzzle", category: "Games", description: "Slide tiles into order", width: 340, loader: () => import("./fifteen") },
  { id: "hanoi", title: "Tower of Hanoi", category: "Games", description: "Move the stack", width: 380, loader: () => import("./hanoi") },
  { id: "nim", title: "Nim", category: "Games", description: "Don't take the last stick", width: 380, loader: () => import("./nim") },
  { id: "asteroids", title: "Asteroids Lite", category: "Games", description: "←→ rotate, ↑ thrust, Space fire", width: 460, loader: () => import("./asteroids") },
  { id: "invaders", title: "Space Invaders", category: "Games", description: "←→ + Space to shoot", width: 440, loader: () => import("./invaders") },
  { id: "frogger", title: "Frogger Crossing", category: "Games", description: "Arrow keys to cross traffic", width: 440, loader: () => import("./frogger") },
  { id: "bubblepop", title: "Bubble Pop", category: "Games", description: "Click bubbles before they escape", width: 420, loader: () => import("./bubblepop") },
  // Games — wave 3 (+21 more)
  { id: "wordle", title: "Word Guess", category: "Games", description: "Guess the 5-letter word", width: 360, loader: () => import("./wordle") },
  { id: "blackjack", title: "Blackjack", category: "Games", description: "Beat the dealer to 21", width: 380, loader: () => import("./blackjack") },
  { id: "roulette", title: "Roulette", category: "Games", description: "Red/Black/Odd/Even", width: 320, loader: () => import("./roulette") },
  { id: "slotmachine", title: "Slot Machine", category: "Games", description: "Spin the reels", width: 360, loader: () => import("./slotmachine") },
  { id: "mastermind", title: "Mastermind", category: "Games", description: "Crack the color code", width: 360, loader: () => import("./mastermind") },
  { id: "gomoku", title: "Gomoku (5-in-row)", category: "Games", description: "Five in a row vs CPU", width: 360, loader: () => import("./gomoku") },
  { id: "plinko", title: "Plinko", category: "Games", description: "Drop balls and score", width: 340, loader: () => import("./plinko") },
  { id: "catcher", title: "Catcher", category: "Games", description: "Catch falling drops", width: 400, loader: () => import("./catcher") },
  { id: "dodger", title: "Dodger", category: "Games", description: "Dodge falling blocks", width: 400, loader: () => import("./dodger") },
  { id: "paint", title: "Paint", category: "Games", description: "Free draw + save PNG", width: 440, loader: () => import("./paint") },
  { id: "maze", title: "Maze", category: "Games", description: "Arrow keys to the exit", width: 420, loader: () => import("./maze") },
  { id: "trivia", title: "Trivia", category: "Games", description: "10 quick questions", width: 420, loader: () => import("./trivia") },
  { id: "balloonpop", title: "Balloon Pop", category: "Games", description: "Pop rising balloons", width: 420, loader: () => import("./balloonpop") },
  { id: "bowling", title: "Bowling", category: "Games", description: "Random rolls + real scoring", width: 360, loader: () => import("./bowling") },
  { id: "golf", title: "Mini Golf 2D", category: "Games", description: "Drag to aim & shoot", width: 440, loader: () => import("./golf") },
  { id: "dotsboxes", title: "Dots & Boxes", category: "Games", description: "Two-player classic", width: 320, loader: () => import("./dotsboxes") },
  { id: "battleship", title: "Battleship", category: "Games", description: "Sink the hidden fleet", width: 360, loader: () => import("./battleship") },
  { id: "emojihunt", title: "Emoji Hunt", category: "Games", description: "Find the target emoji fast", width: 360, loader: () => import("./emojihunt") },
  { id: "cupgame", title: "Cup & Ball", category: "Games", description: "Find the ball under cups", width: 320, loader: () => import("./cupgame") },
  { id: "lottery", title: "Lottery", category: "Games", description: "Pick 6 of 49", width: 360, loader: () => import("./lottery") },
  { id: "snakeladder", title: "Snakes & Ladders", category: "Games", description: "Two-player dice climb", width: 380, loader: () => import("./snakeladder") },
  // Player
  { id: "visualizer", title: "Audio Visualizer", category: "Player", description: "Live spectrum from the loaded media", width: 520, loader: () => import("./visualizer") },
  { id: "sleep-timer", title: "Sleep Timer", category: "Player", description: "Auto-pause/fade after N minutes", width: 360, loader: () => import("./sleep") },
  { id: "eq", title: "10-Band EQ", category: "Player", description: "Parametric EQ presets", width: 460, loader: () => import("./eq") },
  { id: "abrepeat", title: "A↔B Repeat", category: "Player", description: "Loop between two marks", width: 360, loader: () => import("./abrepeat") },
  { id: "framestep", title: "Frame Stepper", category: "Player", description: "Step ±1 frame / second", width: 360, loader: () => import("./framestep") },
  { id: "screenshot", title: "Screenshot", category: "Player", description: "Save current video frame", width: 420, loader: () => import("./screenshot") },
  { id: "frameburst", title: "Frame Burst", category: "Player", description: "Capture 8–16 frames", width: 460, loader: () => import("./frameburst") },
  { id: "speedramp", title: "Playback Speed", category: "Player", description: "0.1× – 4× with presets", width: 380, loader: () => import("./speedramp") },
  { id: "pitchshift", title: "Pitch / Speed", category: "Player", description: "Preserve-pitch toggle", width: 380, loader: () => import("./pitchshift") },
  { id: "subloader", title: "Subtitle Loader", category: "Player", description: "Drag-drop SRT / VTT", width: 460, loader: () => import("./subloader") },
  { id: "subshift", title: "Subtitle Shift", category: "Player", description: "Nudge subs ±ms", width: 360, loader: () => import("./subshift") },
  { id: "audiodelay", title: "Audio Delay", category: "Player", description: "Sync audio offset", width: 380, loader: () => import("./audiodelay") },
  { id: "videorotate", title: "Rotate / Mirror", category: "Player", description: "0/90/180/270 + flip", width: 360, loader: () => import("./videorotate") },
  { id: "aspectcrop", title: "Aspect Ratio", category: "Player", description: "16:9, 21:9, 4:3, 1:1…", width: 380, loader: () => import("./aspectcrop") },
  { id: "colorgrade", title: "Color Grade", category: "Player", description: "Brightness/contrast/hue", width: 420, loader: () => import("./colorgrade") },
  { id: "loopsection", title: "Loop Section", category: "Player", description: "Loop a timeline range", width: 420, loader: () => import("./loopsection") },
  { id: "bookmarks", title: "Bookmarks", category: "Player", description: "Named timestamp marks", width: 420, loader: () => import("./bookmarks") },
  { id: "mediainfo", title: "Media Info", category: "Player", description: "Codec/resolution/state", width: 460, loader: () => import("./mediainfo") },
  { id: "vumeter", title: "VU Meter", category: "Player", description: "Mic peak meter", width: 380, loader: () => import("./vumeter") },
  { id: "oscilloscope", title: "Oscilloscope", category: "Player", description: "Mic waveform scope", width: 520, loader: () => import("./oscilloscope") },
  { id: "micspectrum", title: "Mic Spectrum", category: "Player", description: "Live FFT bars", width: 520, loader: () => import("./micspectrum") },
  { id: "micrecorder", title: "Mic Recorder", category: "Player", description: "Record WebM audio", width: 420, loader: () => import("./micrecorder") },
  { id: "karaoke", title: "Karaoke", category: "Player", description: "Vocal-reduction toggle", width: 380, loader: () => import("./karaoke") },
  // Productivity
  { id: "scratchpad", title: "Scratchpad", category: "Productivity", description: "Quick notes, autosaved", width: 420, loader: () => import("./scratchpad") },
  { id: "calculator", title: "Calculator", category: "Productivity", description: "Quick math + time/FPS converter", width: 320, loader: () => import("./calculator") },
  { id: "stopwatch", title: "Stopwatch", category: "Productivity", description: "Precise timing with laps", width: 320, loader: () => import("./stopwatch") },
  { id: "timer", title: "Countdown Timer", category: "Productivity", description: "Set, start, alert", width: 320, loader: () => import("./timer") },
  { id: "pomodoro", title: "Pomodoro", category: "Productivity", description: "25/5 work-rest cycles", width: 320, loader: () => import("./pomodoro") },
  { id: "todolist", title: "To-Do List", category: "Productivity", description: "Saved across sessions", width: 380, loader: () => import("./todolist") },
  { id: "worldclock", title: "World Clock", category: "Productivity", description: "8 cities at a glance", width: 380, loader: () => import("./worldclock") },
  { id: "unitconvert", title: "Unit Converter", category: "Productivity", description: "Length / weight / temp / volume", width: 420, loader: () => import("./unitconvert") },
  { id: "colorpicker", title: "Color Picker", category: "Productivity", description: "Pick + copy hex / RGB", width: 320, loader: () => import("./colorpicker") },
  { id: "qrgen", title: "QR Generator", category: "Productivity", description: "Encode text / links", width: 320, loader: () => import("./qrgen") },
  { id: "passwordgen", title: "Password Generator", category: "Productivity", description: "Secure random passwords", width: 380, loader: () => import("./passwordgen") },
  { id: "base64", title: "Base64", category: "Productivity", description: "Encode / decode strings", width: 420, loader: () => import("./base64") },
  { id: "jsonformat", title: "JSON Formatter", category: "Productivity", description: "Pretty / minify / validate", width: 460, loader: () => import("./jsonformat") },
  { id: "markdown", title: "Markdown Preview", category: "Productivity", description: "Live preview, autosaved", width: 560, loader: () => import("./markdown") },
  { id: "habit", title: "Habit Tracker", category: "Productivity", description: "14-day streak grid", width: 460, loader: () => import("./habit") },
  { id: "expensetracker", title: "Expense Tracker", category: "Productivity", description: "Track in/out, running total", width: 380, loader: () => import("./expensetracker") },
  { id: "regex", title: "Regex Tester", category: "Productivity", description: "Pattern + flags + match preview", width: 460, loader: () => import("./regex") },
  // Games — wave 4 (+15)
  { id: "circlepop", title: "Circle Pop", category: "Games", description: "Pop circles before they fade", width: 400, loader: () => import("./circlepop") },
  { id: "tank", title: "Tank Arena", category: "Games", description: "Arrows + Space to shoot", width: 440, loader: () => import("./tank") },
  { id: "yatzy", title: "Yatzy Lite", category: "Games", description: "5-round dice scoring", width: 360, loader: () => import("./yatzy") },
  { id: "checkers", title: "Checkers", category: "Games", description: "Classic vs CPU", width: 360, loader: () => import("./checkers") },
  { id: "reversi", title: "Reversi", category: "Games", description: "Othello vs CPU", width: 360, loader: () => import("./reversi") },
  { id: "crash", title: "Crash", category: "Games", description: "Cash out before it busts", width: 360, loader: () => import("./crash") },
  { id: "wordsearch", title: "Word Search", category: "Games", description: "Find hidden words in the grid", width: 360, loader: () => import("./wordsearch") },
  { id: "sudoku4", title: "Mini Sudoku 4×4", category: "Games", description: "Bite-size Sudoku", width: 280, loader: () => import("./sudoku4") },
  { id: "caesar", title: "Caesar Cipher", category: "Games", description: "Decode the shifted message", width: 420, loader: () => import("./caesar") },
  { id: "spelldecode", title: "Unscramble", category: "Games", description: "Rearrange letters into a word", width: 360, loader: () => import("./spelldecode") },
  { id: "quickdraw", title: "Quick Draw", category: "Games", description: "Tap when it turns green", width: 360, loader: () => import("./quickdraw") },
  { id: "snipe", title: "Sniper Range", category: "Games", description: "10-round target shooting", width: 440, loader: () => import("./snipe") },
  { id: "laser", title: "Laser Defender", category: "Games", description: "Rotate + Space to fire", width: 460, loader: () => import("./laser") },
  { id: "orbit", title: "Orbit Swap", category: "Games", description: "Click to swap orbital rings", width: 420, loader: () => import("./orbit") },
  { id: "grow", title: "Grow Garden", category: "Games", description: "Idle clicker garden", width: 360, loader: () => import("./grow") },
  // Productivity — wave 2 (+15)
  { id: "wordcounter", title: "Word Counter", category: "Productivity", description: "Words, chars, reading time", width: 460, loader: () => import("./wordcounter") },
  { id: "tipcalc", title: "Tip Calculator", category: "Productivity", description: "Bill + tip + split", width: 360, loader: () => import("./tipcalc") },
  { id: "agecalc", title: "Age Calculator", category: "Productivity", description: "Years, months, days alive", width: 380, loader: () => import("./agecalc") },
  { id: "bmi", title: "BMI Calculator", category: "Productivity", description: "Metric or imperial", width: 360, loader: () => import("./bmi") },
  { id: "loancalc", title: "Loan / EMI", category: "Productivity", description: "Monthly payment + interest", width: 380, loader: () => import("./loancalc") },
  { id: "percentage", title: "Percentage", category: "Productivity", description: "All the % calculations", width: 360, loader: () => import("./percentage") },
  { id: "uuid", title: "UUID Generator", category: "Productivity", description: "Bulk UUID v4", width: 420, loader: () => import("./uuid") },
  { id: "lorem", title: "Lorem Ipsum", category: "Productivity", description: "Placeholder text", width: 460, loader: () => import("./lorem") },
  { id: "slug", title: "Slug Generator", category: "Productivity", description: "URL-safe slugs", width: 420, loader: () => import("./slug") },
  { id: "hash", title: "Hash Tool", category: "Productivity", description: "SHA-1/256/384/512", width: 460, loader: () => import("./hash") },
  { id: "dateadd", title: "Date Arithmetic", category: "Productivity", description: "Add / subtract days", width: 360, loader: () => import("./dateadd") },
  { id: "currency", title: "Currency Converter", category: "Productivity", description: "Indicative FX rates", width: 420, loader: () => import("./currency") },
  { id: "csvview", title: "CSV Viewer", category: "Productivity", description: "Paste CSV → table", width: 520, loader: () => import("./csvview") },
  { id: "urlparser", title: "URL Parser", category: "Productivity", description: "Inspect any URL", width: 460, loader: () => import("./urlparser") },
  { id: "timesheet", title: "Timesheet", category: "Productivity", description: "Log time per project", width: 420, loader: () => import("./timesheet") },
  { id: "cron", title: "Cron Helper", category: "Productivity", description: "Build & explain cron", width: 420, loader: () => import("./cron") },
  { id: "diff", title: "Text Diff", category: "Productivity", description: "Side-by-side line diff", width: 540, loader: () => import("./diff") },
  { id: "rngpicker", title: "Random Picker", category: "Productivity", description: "Pick / shuffle list", width: 380, loader: () => import("./rngpicker") },
  { id: "scale", title: "Music Scale", category: "Productivity", description: "Major / minor scales + audio", width: 420, loader: () => import("./scale") },
  // Productivity — wave 3 (+20)
  { id: "emojipicker", title: "Emoji Picker", category: "Productivity", description: "Search & copy emojis", width: 460, loader: () => import("./emojipicker") },
  { id: "wifiqr", title: "WiFi QR", category: "Productivity", description: "Generate Wi-Fi join payload", width: 360, loader: () => import("./wifiqr") },
  { id: "useragent", title: "Device Info", category: "Productivity", description: "UA, screen, timezone, threads", width: 460, loader: () => import("./useragent") },
  { id: "textcase", title: "Case Converter", category: "Productivity", description: "UPPER, lower, camel, snake…", width: 460, loader: () => import("./textcase") },
  { id: "textreverse", title: "Text Reverse", category: "Productivity", description: "Chars / words / lines", width: 420, loader: () => import("./textreverse") },
  { id: "binhex", title: "Base Converter", category: "Productivity", description: "Bin / oct / dec / hex", width: 380, loader: () => import("./binhex") },
  { id: "romanconvert", title: "Roman Numerals", category: "Productivity", description: "Decimal ↔ Roman", width: 380, loader: () => import("./romanconvert") },
  { id: "asciitable", title: "ASCII Table", category: "Productivity", description: "Printable ASCII reference", width: 460, loader: () => import("./asciitable") },
  { id: "colorconvert", title: "Color Converter", category: "Productivity", description: "Hex / RGB / HSL", width: 380, loader: () => import("./colorconvert") },
  { id: "gradientgen", title: "Gradient Generator", category: "Productivity", description: "Two-stop CSS gradients", width: 440, loader: () => import("./gradientgen") },
  { id: "shadowgen", title: "Shadow Generator", category: "Productivity", description: "Live box-shadow preview", width: 440, loader: () => import("./shadowgen") },
  { id: "cssunits", title: "CSS Units", category: "Productivity", description: "px / rem / em / pt / vw", width: 380, loader: () => import("./cssunits") },
  { id: "jwtdecode", title: "JWT Decoder", category: "Productivity", description: "Parse header & payload", width: 480, loader: () => import("./jwtdecode") },
  { id: "urlencode", title: "URL Encoder", category: "Productivity", description: "Encode / decode URI", width: 460, loader: () => import("./urlencode") },
  { id: "textsorter", title: "Line Sorter", category: "Productivity", description: "Sort / shuffle / reverse", width: 440, loader: () => import("./textsorter") },
  { id: "dedupe", title: "Dedupe Lines", category: "Productivity", description: "Remove duplicate lines", width: 460, loader: () => import("./dedupe") },
  { id: "countdown", title: "Event Countdown", category: "Productivity", description: "Days/hours to any date", width: 380, loader: () => import("./countdown") },
  { id: "epoch", title: "Epoch Converter", category: "Productivity", description: "Unix timestamp ↔ ISO", width: 460, loader: () => import("./epoch") },
  { id: "randomname", title: "Name Generator", category: "Productivity", description: "Real or fantasy names", width: 380, loader: () => import("./randomname") },
  { id: "tally", title: "Tally Counter", category: "Productivity", description: "Multi-counter clicker", width: 460, loader: () => import("./tally") },
  { id: "scicalc", title: "Scientific Calculator", category: "Productivity", description: "TCSion scientific calculator — full offline popup", width: 487, loader: () => import("./scicalc") },
];


const cache = new Map<string, LazyExoticComponent<ComponentType>>();
export function getFeatureComponent(id: string): LazyExoticComponent<ComponentType> | null {
  const def = FEATURES.find((f) => f.id === id);
  if (!def) return null;
  let comp = cache.get(id);
  if (!comp) { comp = lazy(def.loader); cache.set(id, comp); }
  return comp;
}
