// The 12 hero skins. Each defines a token map (CSS variable overrides)
// plus optional supplementary CSS scoped under `[data-skin="<id>"]`.
// These hero definitions are tiny strings and stay in the main bundle —
// switching skins is a single style-tag swap, no React re-render of the
// video element, no chunk fetch.

import type { SkinHero } from "./types";
import { MEGA_HEROES } from "./megaHeroes";
import { WAVE6_HEROES } from "./wave6Heroes";
import { PREMIUM_HEROES } from "./premiumHeroes";
import { WAVE7_HEROES } from "./wave7Heroes";
import { PREMIUM_WAVE } from "./premiumWave";

const SF = '"SF Pro Display", "SF Pro Text", -apple-system, BlinkMacSystemFont, sans-serif';
const ROBOTO = '"Roboto", "Helvetica Neue", Arial, sans-serif';
const NETSANS = '"Netflix Sans", "Helvetica Neue", Arial, sans-serif';
const CIRCULAR = '"Circular", "Helvetica Neue", Arial, sans-serif';
const PIXEL = '"VT323", "Press Start 2P", ui-monospace, monospace';
const MONO = '"JetBrains Mono", ui-monospace, "SF Mono", Consolas, monospace';
const SEGOE = '"Segoe UI", Tahoma, sans-serif';
const SPACE = '"Space Grotesk", "Inter", sans-serif';

// 10 additional typefaces for the second wave of heroes. Each is a distinct
// voice and loaded on demand via the font preload tag in the SkinProvider.
const PLAYFAIR = '"Playfair Display", "Cormorant Garamond", Georgia, serif';
const BEBAS = '"Bebas Neue", "Oswald", Impact, sans-serif';
const ORBITRON = '"Orbitron", "Audiowide", "Space Mono", monospace';
const RAJDHANI = '"Rajdhani", "Saira", "Eurostile", sans-serif';
const IBMPLEX = '"IBM Plex Mono", "Source Code Pro", ui-monospace, monospace';
const LIBRE_CAS = '"Libre Caslon Text", "EB Garamond", "Times New Roman", serif';
const POPPINS = '"Poppins", "Nunito Sans", "Helvetica Neue", sans-serif';
const PRESS_START = '"Press Start 2P", "VT323", ui-monospace, monospace';
const CINZEL = '"Cinzel", "Trajan Pro", "Times New Roman", serif';
const SHIPPORI = '"Shippori Mincho", "Noto Serif JP", "Yu Mincho", serif';

// Wave 3 — 10 additional typefaces, one per new hero.
const MANROPE = '"Manrope", "Inter", -apple-system, sans-serif';
const MAJOR_MONO = '"Major Mono Display", "Space Mono", ui-monospace, monospace';
const QUICKSAND = '"Quicksand", "Nunito", "Helvetica Neue", sans-serif';
const TYPEWRITER = '"Special Elite", "Courier Prime", "Courier New", monospace';
const AUDIOWIDE = '"Audiowide", "Orbitron", "Space Mono", monospace';
const BANGERS = '"Bangers", "Bebas Neue", Impact, sans-serif';
const CAVEAT = '"Caveat", "Kalam", "Comic Sans MS", cursive';
const FRAUNCES = '"Fraunces", "Cormorant Garamond", Georgia, serif';
const SYNE = '"Syne", "Space Grotesk", "Inter", sans-serif';
const ANTON = '"Anton", "Oswald", Impact, sans-serif';

// Wave 4 — 30 additional typefaces. Loaded on demand by the font preload
// tag in __root.tsx with display=swap, so they never block first paint.
const DM_SERIF = '"DM Serif Display", "Playfair Display", Georgia, serif';
const SPACE_MONO = '"Space Mono", "JetBrains Mono", ui-monospace, monospace';
const KARLA = '"Karla", "Inter", -apple-system, sans-serif';
const RUBIK = '"Rubik", "Inter", -apple-system, sans-serif';
const RIGHTEOUS = '"Righteous", "Anton", Impact, sans-serif';
const ALFA_SLAB = '"Alfa Slab One", "Bangers", Impact, serif';
const PT_SERIF = '"PT Serif", "Source Serif Pro", Georgia, serif';
const CORMORANT = '"Cormorant Garamond", "EB Garamond", Georgia, serif';
const TEKO = '"Teko", "Rajdhani", "Eurostile", sans-serif';
const CHAKRA = '"Chakra Petch", "Rajdhani", "Eurostile", sans-serif';
const VIGA = '"Viga", "Poppins", "Helvetica Neue", sans-serif';
const PACIFICO = '"Pacifico", "Caveat", cursive';
const SACRAMENTO = '"Sacramento", "Allura", cursive';
const KALAM = '"Kalam", "Caveat", "Comic Sans MS", cursive';
const PERMANENT = '"Permanent Marker", "Bangers", Impact, sans-serif';
const MONOTON = '"Monoton", "Audiowide", "Orbitron", monospace';
const STALINIST = '"Stalinist One", "Bebas Neue", Impact, sans-serif';
const FASTER_ONE = '"Faster One", "Audiowide", "Orbitron", monospace';
const UNIFRAKTUR = '"UnifrakturCook", "Cinzel", Georgia, serif';
const ZILLA = '"Zilla Slab", "PT Serif", "Source Serif Pro", serif';
const ABRIL = '"Abril Fatface", "Playfair Display", Georgia, serif';
const EXO = '"Exo 2", "Rajdhani", sans-serif';
const COURIER_PRIME = '"Courier Prime", "Special Elite", "Courier New", monospace';
const SHARE_TECH = '"Share Tech Mono", "VT323", ui-monospace, monospace';
const PIRATA = '"Pirata One", "UnifrakturCook", Georgia, serif';
const GRUPPO = '"Gruppo", "Audiowide", "Orbitron", monospace';
const NIXIE = '"Nixie One", "Space Mono", ui-monospace, monospace';
const COMFORTAA = '"Comfortaa", "Quicksand", "Nunito", sans-serif';
const ABEEZEE = '"ABeeZee", "Karla", "Inter", sans-serif';
const SILKSCREEN = '"Silkscreen", "Press Start 2P", ui-monospace, monospace';


const INTER_TIGHT = '"Inter Tight", "Inter", -apple-system, BlinkMacSystemFont, sans-serif';
const INSTRUMENT = '"Instrument Serif", "Cormorant Garamond", Georgia, serif';

export const HEROES: SkinHero[] = [
  ...PREMIUM_WAVE,
  ...PREMIUM_HEROES,
  ...MEGA_HEROES,
  ...WAVE6_HEROES,
  ...WAVE7_HEROES,
  {
    id: "vlc-classic",
    name: "VLC Classic",
    tagline: "The original. Orange traffic cone heritage.",
    tags: ["dark", "default", "pro"],
    tokens: {},
  },

  {
    id: "midnight-linear",
    name: "Midnight Linear",
    tagline: "Indigo ink. Hairline borders. Editorial serif moments.",
    tags: ["dark", "minimal", "pro", "featured", "premium", "blue"],
    tokens: {
      "--vlc-bg-base": "oklch(0.14 0.02 265)",
      "--vlc-bg-surface": "oklch(0.18 0.025 265)",
      "--vlc-bg-elevated": "oklch(0.22 0.03 265)",
      "--vlc-bg-sunken": "oklch(0.10 0.015 265)",
      "--vlc-border-subtle": "oklch(1 0 0 / 0.06)",
      "--vlc-border-normal": "oklch(1 0 0 / 0.10)",
      "--vlc-border-strong": "oklch(1 0 0 / 0.18)",
      "--vlc-text-primary": "oklch(0.98 0 0)",
      "--vlc-text-secondary": "oklch(0.72 0.01 265)",
      "--vlc-text-ghost": "oklch(0.52 0.01 265)",
      "--vlc-accent": "oklch(0.68 0.18 265)",
      "--vlc-accent-hover": "oklch(0.74 0.18 265)",
      "--vlc-accent-dim": "oklch(0.68 0.18 265 / 0.14)",
      "--vlc-accent-text": "oklch(0.82 0.14 265)",
      "--vlc-seek-played": "oklch(0.68 0.18 265)",
      "--vlc-seek-thumb": "oklch(0.92 0.05 265)",
      "--vlc-seek-buffered": "oklch(1 0 0 / 0.18)",
      "--vlc-seek-track": "oklch(1 0 0 / 0.08)",
      "--vlc-font-ui": INTER_TIGHT,
      "--vlc-font-mono": '"JetBrains Mono", ui-monospace, SFMono-Regular, monospace',
      "--vlc-font-display": INSTRUMENT,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "10px",
      "--vlc-radius-lg": "14px",
      "--vlc-control-radius": "8px",
      "--vlc-control-hover": "oklch(1 0 0 / 0.06)",
      "--vlc-transition-fast": "140ms cubic-bezier(0.2, 0, 0, 1)",
      "--vlc-shadow-popup": "0 1px 0 oklch(1 0 0 / 0.05) inset, 0 12px 32px -8px oklch(0 0 0 / 0.6), 0 4px 12px -4px oklch(0 0 0 / 0.4)",
    },
    extraCss: "",
  },





  {
    id: "apple",
    name: "Apple QuickTime",
    tagline: "Translucent glass. Pill controls. SF Pro.",
    tags: ["light", "minimal", "glass"],
    tokens: {
      "--vlc-bg-base": "#1c1c1e",
      "--vlc-bg-surface": "rgba(40,40,42,0.72)",
      "--vlc-bg-elevated": "rgba(58,58,60,0.92)",
      "--vlc-bg-sunken": "rgba(28,28,30,0.85)",
      "--vlc-border-subtle": "rgba(255,255,255,0.07)",
      "--vlc-border-normal": "rgba(255,255,255,0.14)",
      "--vlc-border-strong": "rgba(255,255,255,0.26)",
      "--vlc-accent": "#0a84ff",
      "--vlc-accent-hover": "#0070e0",
      "--vlc-accent-dim": "rgba(10,132,255,0.18)",
      "--vlc-accent-text": "#5eb0ff",
      "--vlc-seek-played": "#ffffff",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-font-ui": SF,
      "--vlc-radius-sm": "8px",
      "--vlc-radius-md": "14px",
      "--vlc-radius-lg": "22px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "youtube",
    name: "YouTube",
    tagline: "Red accent. Roboto. Bottom-only progress.",
    tags: ["dark", "red", "video"],
    tokens: {
      "--vlc-bg-base": "#0f0f0f",
      "--vlc-bg-surface": "#0f0f0f",
      "--vlc-bg-elevated": "#212121",
      "--vlc-bg-sunken": "#0f0f0f",
      "--vlc-border-subtle": "rgba(255,255,255,0.04)",
      "--vlc-border-normal": "rgba(255,255,255,0.08)",
      "--vlc-accent": "#ff0033",
      "--vlc-accent-hover": "#cc0029",
      "--vlc-accent-dim": "rgba(255,0,51,0.18)",
      "--vlc-accent-text": "#ff4d6d",
      "--vlc-seek-played": "#ff0033",
      "--vlc-seek-thumb": "#ff0033",
      "--vlc-seek-buffered": "rgba(255,255,255,0.35)",
      "--vlc-seek-track": "rgba(255,255,255,0.18)",
      "--vlc-font-ui": ROBOTO,
      "--vlc-control-radius": "999px",
      "--vlc-radius-sm": "4px",
      "--vlc-radius-md": "12px",
    },
    extraCss: "",
  },

  {
    id: "netflix",
    name: "Netflix",
    tagline: "Bold red. Cinematic black. Top fade.",
    tags: ["dark", "red", "cinema"],
    tokens: {
      "--vlc-bg-base": "#000000",
      "--vlc-bg-surface": "rgba(20,20,20,0.85)",
      "--vlc-bg-elevated": "#181818",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,255,255,0.05)",
      "--vlc-border-normal": "rgba(255,255,255,0.12)",
      "--vlc-accent": "#e50914",
      "--vlc-accent-hover": "#b8070f",
      "--vlc-accent-dim": "rgba(229,9,20,0.22)",
      "--vlc-accent-text": "#ff3d4a",
      "--vlc-seek-played": "#e50914",
      "--vlc-seek-thumb": "#e50914",
      "--vlc-font-ui": NETSANS,
      "--vlc-control-radius": "4px",
    },
  },

  {
    id: "spotify",
    name: "Spotify",
    tagline: "Green energy. Rounded cards. Circular.",
    tags: ["dark", "green", "music"],
    tokens: {
      "--vlc-bg-base": "#121212",
      "--vlc-bg-surface": "#181818",
      "--vlc-bg-elevated": "#282828",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,255,255,0.05)",
      "--vlc-border-normal": "rgba(255,255,255,0.10)",
      "--vlc-accent": "#1db954",
      "--vlc-accent-hover": "#179443",
      "--vlc-accent-dim": "rgba(29,185,84,0.18)",
      "--vlc-accent-text": "#4ade80",
      "--vlc-seek-played": "#1db954",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-font-ui": CIRCULAR,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "12px",
      "--vlc-radius-lg": "16px",
      "--vlc-control-radius": "999px",
    },
  },

  {
    id: "winamp",
    name: "Winamp Classic",
    tagline: "Beveled metal. LCD time. Pixel-perfect.",
    tags: ["retro", "beveled", "skin"],
    tokens: {
      "--vlc-bg-base": "#1a1a1a",
      "--vlc-bg-surface": "linear-gradient(180deg,#5a5a5a 0%,#2a2a2a 100%)",
      "--vlc-bg-elevated": "#3a3a3a",
      "--vlc-bg-sunken": "#0a0a0a",
      "--vlc-border-subtle": "#5c5c5c",
      "--vlc-border-normal": "#7c7c7c",
      "--vlc-border-strong": "#9c9c9c",
      "--vlc-accent": "#00ff66",
      "--vlc-accent-hover": "#00cc52",
      "--vlc-accent-dim": "rgba(0,255,102,0.15)",
      "--vlc-accent-text": "#00ff66",
      "--vlc-seek-played": "#00ff66",
      "--vlc-seek-thumb": "#c4c4c4",
      "--vlc-text-primary": "#00ff66",
      "--vlc-text-secondary": "rgba(0,255,102,0.7)",
      "--vlc-font-ui": PIXEL,
      "--vlc-font-mono": PIXEL,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
      "--vlc-radius-lg": "0",
    },
    extraCss: "",
  },

  {
    id: "mpc",
    name: "MPC-HC",
    tagline: "Flat Windows toolbar. Dense. Pragmatic.",
    tags: ["retro", "pro", "dense"],
    tokens: {
      "--vlc-bg-base": "#ece9d8",
      "--vlc-bg-surface": "#d4d0c8",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#ffffff",
      "--vlc-border-subtle": "#808080",
      "--vlc-border-normal": "#606060",
      "--vlc-border-strong": "#404040",
      "--vlc-accent": "#316ac5",
      "--vlc-accent-hover": "#1f4f99",
      "--vlc-accent-dim": "rgba(49,106,197,0.22)",
      "--vlc-accent-text": "#316ac5",
      "--vlc-seek-played": "#316ac5",
      "--vlc-seek-thumb": "#316ac5",
      "--vlc-seek-track": "rgba(0,0,0,0.18)",
      "--vlc-text-primary": "#000000",
      "--vlc-text-secondary": "rgba(0,0,0,0.65)",
      "--vlc-text-ghost": "rgba(0,0,0,0.4)",
      "--vlc-font-ui": SEGOE,
      "--vlc-control-radius": "2px",
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "3px",
    },
    extraCss: "",
  },

  {
    id: "plex",
    name: "Plex",
    tagline: "Slate. Amber accent. Cinematic.",
    tags: ["dark", "amber", "cinema"],
    tokens: {
      "--vlc-bg-base": "#1f2326",
      "--vlc-bg-surface": "#282d31",
      "--vlc-bg-elevated": "#323840",
      "--vlc-bg-sunken": "#141618",
      "--vlc-border-subtle": "rgba(255,255,255,0.06)",
      "--vlc-border-normal": "rgba(255,255,255,0.12)",
      "--vlc-accent": "#e5a00d",
      "--vlc-accent-hover": "#c2870a",
      "--vlc-accent-dim": "rgba(229,160,13,0.18)",
      "--vlc-accent-text": "#f7c34d",
      "--vlc-seek-played": "#e5a00d",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-font-ui": SF,
      "--vlc-radius-md": "10px",
      "--vlc-control-radius": "8px",
    },
  },

  {
    id: "brutalist",
    name: "Brutalist",
    tagline: "Hard borders. No radius. Maximum contrast.",
    tags: ["light", "experimental", "mono"],
    tokens: {
      "--vlc-bg-base": "#ffffff",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0f0f0",
      "--vlc-border-subtle": "#000000",
      "--vlc-border-normal": "#000000",
      "--vlc-border-strong": "#000000",
      "--vlc-accent": "#000000",
      "--vlc-accent-hover": "#222222",
      "--vlc-accent-dim": "rgba(0,0,0,0.1)",
      "--vlc-accent-text": "#000000",
      "--vlc-seek-played": "#000000",
      "--vlc-seek-thumb": "#000000",
      "--vlc-seek-track": "#e0e0e0",
      "--vlc-text-primary": "#000000",
      "--vlc-text-secondary": "rgba(0,0,0,0.7)",
      "--vlc-text-ghost": "rgba(0,0,0,0.45)",
      "--vlc-font-ui": MONO,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
      "--vlc-radius-lg": "0",
    },
    extraCss: "",
  },

  {
    id: "terminal",
    name: "Terminal CLI",
    tagline: "Phosphor green. Monospace everywhere.",
    tags: ["dark", "green", "mono", "retro"],
    tokens: {
      "--vlc-bg-base": "#000000",
      "--vlc-bg-surface": "#040a04",
      "--vlc-bg-elevated": "#0a140a",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(0,255,102,0.18)",
      "--vlc-border-normal": "rgba(0,255,102,0.35)",
      "--vlc-border-strong": "rgba(0,255,102,0.6)",
      "--vlc-accent": "#00ff66",
      "--vlc-accent-hover": "#00cc52",
      "--vlc-accent-dim": "rgba(0,255,102,0.12)",
      "--vlc-accent-text": "#7dff9c",
      "--vlc-seek-played": "#00ff66",
      "--vlc-seek-thumb": "#00ff66",
      "--vlc-seek-track": "rgba(0,255,102,0.15)",
      "--vlc-text-primary": "#00ff66",
      "--vlc-text-secondary": "rgba(0,255,102,0.7)",
      "--vlc-text-ghost": "rgba(0,255,102,0.4)",
      "--vlc-font-ui": MONO,
      "--vlc-font-mono": MONO,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
    },
    extraCss: "",
  },

  {
    id: "cinema",
    name: "Cinema",
    tagline: "Bezel-less. Festival HUD. Letterbox.",
    tags: ["dark", "minimal", "cinema"],
    tokens: {
      "--vlc-bg-base": "#000000",
      "--vlc-bg-surface": "rgba(0,0,0,0.55)",
      "--vlc-bg-elevated": "rgba(20,20,20,0.92)",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,255,255,0.04)",
      "--vlc-border-normal": "rgba(255,255,255,0.08)",
      "--vlc-accent": "#f5e6c8",
      "--vlc-accent-hover": "#e0cfa8",
      "--vlc-accent-dim": "rgba(245,230,200,0.14)",
      "--vlc-accent-text": "#f5e6c8",
      "--vlc-seek-played": "#f5e6c8",
      "--vlc-seek-thumb": "#f5e6c8",
      "--vlc-font-ui": SPACE,
      "--vlc-control-radius": "2px",
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "4px",
    },
    extraCss: "",
  },

  {
    id: "neon",
    name: "Neon Cyberpunk",
    tagline: "Magenta + cyan. Chromatic glow.",
    tags: ["dark", "neon", "experimental"],
    tokens: {
      "--vlc-bg-base": "#0a001a",
      "--vlc-bg-surface": "#15002e",
      "--vlc-bg-elevated": "#22004a",
      "--vlc-bg-sunken": "#05000d",
      "--vlc-border-subtle": "rgba(255,0,200,0.18)",
      "--vlc-border-normal": "rgba(255,0,200,0.4)",
      "--vlc-border-strong": "rgba(0,255,255,0.6)",
      "--vlc-accent": "#ff00c8",
      "--vlc-accent-hover": "#cc009f",
      "--vlc-accent-dim": "rgba(255,0,200,0.2)",
      "--vlc-accent-text": "#00f0ff",
      "--vlc-seek-played": "#ff00c8",
      "--vlc-seek-thumb": "#00f0ff",
      "--vlc-seek-buffered": "rgba(0,240,255,0.3)",
      "--vlc-text-primary": "#f0c8ff",
      "--vlc-text-secondary": "rgba(240,200,255,0.7)",
      "--vlc-font-ui": SPACE,
      "--vlc-control-radius": "2px",
    },
    extraCss: "",
  },

  // ─── Wave 2 — 10 additional hero skins, each with its own typeface ───

  {
    id: "editorial",
    name: "Editorial Serif",
    tagline: "Playfair Display. Magazine cover energy.",
    tags: ["light", "serif", "elegant"],
    tokens: {
      "--vlc-bg-base": "#faf7f2",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0ece4",
      "--vlc-border-subtle": "rgba(0,0,0,0.06)",
      "--vlc-border-normal": "rgba(0,0,0,0.14)",
      "--vlc-border-strong": "#1a1a1a",
      "--vlc-accent": "#1a1a1a",
      "--vlc-accent-hover": "#000000",
      "--vlc-accent-dim": "rgba(26,26,26,0.08)",
      "--vlc-accent-text": "#1a1a1a",
      "--vlc-seek-played": "#1a1a1a",
      "--vlc-seek-thumb": "#1a1a1a",
      "--vlc-seek-track": "rgba(0,0,0,0.12)",
      "--vlc-text-primary": "#1a1a1a",
      "--vlc-text-secondary": "rgba(26,26,26,0.65)",
      "--vlc-text-ghost": "rgba(26,26,26,0.4)",
      "--vlc-font-ui": PLAYFAIR,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
    },
    extraCss: "",
  },

  {
    id: "bebas-poster",
    name: "Bebas Poster",
    tagline: "Bebas Neue. Tall caps. Festival poster.",
    tags: ["dark", "bold", "poster"],
    tokens: {
      "--vlc-bg-base": "#101010",
      "--vlc-bg-surface": "#181818",
      "--vlc-bg-elevated": "#222222",
      "--vlc-bg-sunken": "#0a0a0a",
      "--vlc-border-subtle": "rgba(255,255,255,0.06)",
      "--vlc-border-normal": "rgba(255,255,255,0.12)",
      "--vlc-accent": "#ffd400",
      "--vlc-accent-hover": "#e0bb00",
      "--vlc-accent-dim": "rgba(255,212,0,0.18)",
      "--vlc-accent-text": "#ffd400",
      "--vlc-seek-played": "#ffd400",
      "--vlc-seek-thumb": "#ffd400",
      "--vlc-font-ui": BEBAS,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "tron",
    name: "TRON Grid",
    tagline: "Orbitron. Cyan grid. Light cycle.",
    tags: ["dark", "neon", "scifi", "cyan"],
    tokens: {
      "--vlc-bg-base": "#000814",
      "--vlc-bg-surface": "#001f3f",
      "--vlc-bg-elevated": "#003366",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(0,229,255,0.18)",
      "--vlc-border-normal": "rgba(0,229,255,0.45)",
      "--vlc-border-strong": "rgba(0,229,255,0.8)",
      "--vlc-accent": "#00e5ff",
      "--vlc-accent-hover": "#00b8d4",
      "--vlc-accent-dim": "rgba(0,229,255,0.15)",
      "--vlc-accent-text": "#7df9ff",
      "--vlc-seek-played": "#00e5ff",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-seek-track": "rgba(0,229,255,0.12)",
      "--vlc-text-primary": "#c6f7ff",
      "--vlc-text-secondary": "rgba(198,247,255,0.7)",
      "--vlc-font-ui": ORBITRON,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "hud-tactical",
    name: "Tactical HUD",
    tagline: "Rajdhani. Military readout. Amber on black.",
    tags: ["dark", "tactical", "amber", "mono"],
    tokens: {
      "--vlc-bg-base": "#0a0a08",
      "--vlc-bg-surface": "#15140d",
      "--vlc-bg-elevated": "#1f1d12",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,176,0,0.2)",
      "--vlc-border-normal": "rgba(255,176,0,0.45)",
      "--vlc-border-strong": "#ffb000",
      "--vlc-accent": "#ffb000",
      "--vlc-accent-hover": "#cc8c00",
      "--vlc-accent-dim": "rgba(255,176,0,0.14)",
      "--vlc-accent-text": "#ffd966",
      "--vlc-seek-played": "#ffb000",
      "--vlc-seek-thumb": "#ffb000",
      "--vlc-seek-track": "rgba(255,176,0,0.15)",
      "--vlc-text-primary": "#ffd966",
      "--vlc-text-secondary": "rgba(255,217,102,0.7)",
      "--vlc-font-ui": RAJDHANI,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "plex-mono",
    name: "Developer Console",
    tagline: "IBM Plex Mono. Print-quality dev tools.",
    tags: ["dark", "mono", "developer"],
    tokens: {
      "--vlc-bg-base": "#161616",
      "--vlc-bg-surface": "#262626",
      "--vlc-bg-elevated": "#393939",
      "--vlc-bg-sunken": "#0e0e0e",
      "--vlc-border-subtle": "rgba(255,255,255,0.08)",
      "--vlc-border-normal": "rgba(255,255,255,0.18)",
      "--vlc-accent": "#78a9ff",
      "--vlc-accent-hover": "#4589ff",
      "--vlc-accent-dim": "rgba(120,169,255,0.16)",
      "--vlc-accent-text": "#a6c8ff",
      "--vlc-seek-played": "#78a9ff",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-font-ui": IBMPLEX,
      "--vlc-font-mono": IBMPLEX,
      "--vlc-control-radius": "2px",
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "4px",
    },
    extraCss: "",
  },

  {
    id: "newsprint",
    name: "Newsprint",
    tagline: "Libre Caslon. Broadsheet headline grid.",
    tags: ["light", "serif", "editorial"],
    tokens: {
      "--vlc-bg-base": "#f4f1ea",
      "--vlc-bg-surface": "#ebe7dc",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#dcd6c6",
      "--vlc-border-subtle": "rgba(40,30,20,0.1)",
      "--vlc-border-normal": "rgba(40,30,20,0.25)",
      "--vlc-border-strong": "#281e14",
      "--vlc-accent": "#8b1a1a",
      "--vlc-accent-hover": "#6b1313",
      "--vlc-accent-dim": "rgba(139,26,26,0.1)",
      "--vlc-accent-text": "#8b1a1a",
      "--vlc-seek-played": "#8b1a1a",
      "--vlc-seek-thumb": "#281e14",
      "--vlc-seek-track": "rgba(40,30,20,0.18)",
      "--vlc-text-primary": "#281e14",
      "--vlc-text-secondary": "rgba(40,30,20,0.7)",
      "--vlc-text-ghost": "rgba(40,30,20,0.45)",
      "--vlc-font-ui": LIBRE_CAS,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "candy",
    name: "Candy Pop",
    tagline: "Poppins. Bubblegum gradients. Soft & sweet.",
    tags: ["light", "playful", "gradient", "pink"],
    tokens: {
      "--vlc-bg-base": "linear-gradient(135deg,#fff0f6 0%,#f0e7ff 50%,#e7f0ff 100%)",
      "--vlc-bg-surface": "rgba(255,255,255,0.7)",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "rgba(255,255,255,0.5)",
      "--vlc-border-subtle": "rgba(180,120,255,0.18)",
      "--vlc-border-normal": "rgba(180,120,255,0.32)",
      "--vlc-accent": "#ff5ea8",
      "--vlc-accent-hover": "#e63d8a",
      "--vlc-accent-dim": "rgba(255,94,168,0.18)",
      "--vlc-accent-text": "#c2227a",
      "--vlc-seek-played": "#ff5ea8",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#3a1d4a",
      "--vlc-text-secondary": "rgba(58,29,74,0.7)",
      "--vlc-font-ui": POPPINS,
      "--vlc-radius-sm": "10px",
      "--vlc-radius-md": "18px",
      "--vlc-radius-lg": "28px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "arcade",
    name: "8-Bit Arcade",
    tagline: "Press Start 2P. Chunky pixels. Coin-op heart.",
    tags: ["retro", "pixel", "game"],
    tokens: {
      "--vlc-bg-base": "#1a0033",
      "--vlc-bg-surface": "#2d0066",
      "--vlc-bg-elevated": "#4d0099",
      "--vlc-bg-sunken": "#0a0019",
      "--vlc-border-subtle": "#ff00aa",
      "--vlc-border-normal": "#ff00aa",
      "--vlc-border-strong": "#ffff00",
      "--vlc-accent": "#ffff00",
      "--vlc-accent-hover": "#cccc00",
      "--vlc-accent-dim": "rgba(255,255,0,0.2)",
      "--vlc-accent-text": "#ffff00",
      "--vlc-seek-played": "#ffff00",
      "--vlc-seek-thumb": "#ff00aa",
      "--vlc-seek-track": "#000000",
      "--vlc-text-primary": "#ffffff",
      "--vlc-text-secondary": "#ff00aa",
      "--vlc-font-ui": PRESS_START,
      "--vlc-font-mono": PRESS_START,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
      "--vlc-font-size-sm": "9px",
      "--vlc-font-size-md": "10px",
    },
    extraCss: "",
  },

  {
    id: "imperial",
    name: "Imperial Gold",
    tagline: "Cinzel. Ornamental. Roman triumph.",
    tags: ["dark", "luxury", "serif", "gold"],
    tokens: {
      "--vlc-bg-base": "#0f0a05",
      "--vlc-bg-surface": "#1a1208",
      "--vlc-bg-elevated": "#2a1d0e",
      "--vlc-bg-sunken": "#080503",
      "--vlc-border-subtle": "rgba(212,175,55,0.18)",
      "--vlc-border-normal": "rgba(212,175,55,0.4)",
      "--vlc-border-strong": "#d4af37",
      "--vlc-accent": "#d4af37",
      "--vlc-accent-hover": "#b8941f",
      "--vlc-accent-dim": "rgba(212,175,55,0.14)",
      "--vlc-accent-text": "#f0d76c",
      "--vlc-seek-played": "linear-gradient(90deg,#d4af37,#f0d76c,#d4af37)",
      "--vlc-seek-thumb": "#f0d76c",
      "--vlc-text-primary": "#f0d76c",
      "--vlc-text-secondary": "rgba(240,215,108,0.7)",
      "--vlc-font-ui": CINZEL,
      "--vlc-control-radius": "2px",
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "4px",
    },
    extraCss: "",
  },

  {
    id: "wabi-sabi",
    name: "Wabi-Sabi",
    tagline: "Shippori Mincho. Sumi-e ink. Quiet asymmetry.",
    tags: ["light", "minimal", "serif", "zen"],
    tokens: {
      "--vlc-bg-base": "#f5f2eb",
      "--vlc-bg-surface": "#ebe6db",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#e0dac9",
      "--vlc-border-subtle": "rgba(30,25,20,0.08)",
      "--vlc-border-normal": "rgba(30,25,20,0.2)",
      "--vlc-border-strong": "#1e1914",
      "--vlc-accent": "#1e1914",
      "--vlc-accent-hover": "#000000",
      "--vlc-accent-dim": "rgba(30,25,20,0.08)",
      "--vlc-accent-text": "#1e1914",
      "--vlc-seek-played": "#1e1914",
      "--vlc-seek-thumb": "#1e1914",
      "--vlc-seek-track": "rgba(30,25,20,0.14)",
      "--vlc-text-primary": "#1e1914",
      "--vlc-text-secondary": "rgba(30,25,20,0.62)",
      "--vlc-text-ghost": "rgba(30,25,20,0.4)",
      "--vlc-font-ui": SHIPPORI,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
    },
    extraCss: "",
  },

  // ─── Wave 3 — 10 additional heroes. Each is a complete new identity. ───

  {
    id: "aurora-glass",
    name: "Aurora Glass",
    tagline: "Manrope. Flowing aurora. Deep glassmorphism.",
    tags: ["dark", "glass", "gradient"],
    tokens: {
      "--vlc-bg-base": "radial-gradient(at 20% 10%, #1a2a5e 0%, transparent 50%), radial-gradient(at 80% 60%, #4a1a6e 0%, transparent 55%), #06081a",
      "--vlc-bg-surface": "rgba(20,30,60,0.45)",
      "--vlc-bg-elevated": "rgba(40,55,95,0.65)",
      "--vlc-bg-sunken": "rgba(10,15,35,0.55)",
      "--vlc-border-subtle": "rgba(180,200,255,0.08)",
      "--vlc-border-normal": "rgba(180,200,255,0.18)",
      "--vlc-accent": "#7df9ff",
      "--vlc-accent-hover": "#4ad8e0",
      "--vlc-accent-dim": "rgba(125,249,255,0.16)",
      "--vlc-accent-text": "#b8fbff",
      "--vlc-seek-played": "linear-gradient(90deg,#7df9ff,#a78bfa,#ff7de1)",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e8edff",
      "--vlc-text-secondary": "rgba(232,237,255,0.7)",
      "--vlc-font-ui": MANROPE,
      "--vlc-radius-sm": "10px",
      "--vlc-radius-md": "18px",
      "--vlc-radius-lg": "26px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "vaporwave",
    name: "Vaporwave 90",
    tagline: "Major Mono. Pink horizon. Sun-drenched grid.",
    tags: ["retro", "neon", "gradient", "pink"],
    tokens: {
      "--vlc-bg-base": "linear-gradient(180deg,#0a0218 0%,#3a0a4a 30%,#1a0a3a 70%,#0a0218 100%)",
      "--vlc-bg-surface": "rgba(20,5,40,0.7)",
      "--vlc-bg-elevated": "rgba(40,10,70,0.85)",
      "--vlc-bg-sunken": "rgba(10,0,25,0.7)",
      "--vlc-border-subtle": "rgba(255,113,206,0.3)",
      "--vlc-border-normal": "#ff71ce",
      "--vlc-border-strong": "#01cdfe",
      "--vlc-accent": "#ff71ce",
      "--vlc-accent-hover": "#e04faf",
      "--vlc-accent-dim": "rgba(255,113,206,0.2)",
      "--vlc-accent-text": "#01cdfe",
      "--vlc-seek-played": "linear-gradient(90deg,#ff71ce,#01cdfe)",
      "--vlc-seek-thumb": "#fffb96",
      "--vlc-text-primary": "#ffffff",
      "--vlc-text-secondary": "rgba(255,255,255,0.78)",
      "--vlc-text-ghost": "rgba(255,255,255,0.52)",
      "--vlc-font-ui": MAJOR_MONO,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "origami",
    name: "Origami Paper",
    tagline: "Quicksand. Folded paper. Soft pastel cream.",
    tags: ["light", "soft", "paper"],
    tokens: {
      "--vlc-bg-base": "#fbf8f3",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0ebe0",
      "--vlc-border-subtle": "rgba(120,100,80,0.1)",
      "--vlc-border-normal": "rgba(120,100,80,0.18)",
      "--vlc-accent": "#f08a5d",
      "--vlc-accent-hover": "#d96e42",
      "--vlc-accent-dim": "rgba(240,138,93,0.16)",
      "--vlc-accent-text": "#c45a30",
      "--vlc-seek-played": "#f08a5d",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#3d2f24",
      "--vlc-text-secondary": "rgba(61,47,36,0.7)",
      "--vlc-font-ui": QUICKSAND,
      "--vlc-radius-sm": "8px",
      "--vlc-radius-md": "16px",
      "--vlc-radius-lg": "24px",
      "--vlc-control-radius": "14px",
    },
    extraCss: "",
  },

  {
    id: "blueprint",
    name: "Blueprint",
    tagline: "Special Elite. Architect's grid. Cyan on navy.",
    tags: ["dark", "blue", "mono", "drafting"],
    tokens: {
      "--vlc-bg-base": "#0d2645",
      "--vlc-bg-surface": "#103056",
      "--vlc-bg-elevated": "#163d6c",
      "--vlc-bg-sunken": "#081a30",
      "--vlc-border-subtle": "rgba(170,220,255,0.18)",
      "--vlc-border-normal": "rgba(170,220,255,0.4)",
      "--vlc-border-strong": "#aadcff",
      "--vlc-accent": "#aadcff",
      "--vlc-accent-hover": "#7cc4ff",
      "--vlc-accent-dim": "rgba(170,220,255,0.14)",
      "--vlc-accent-text": "#e0f2ff",
      "--vlc-seek-played": "#aadcff",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e0f2ff",
      "--vlc-text-secondary": "rgba(224,242,255,0.7)",
      "--vlc-font-ui": TYPEWRITER,
      "--vlc-font-mono": TYPEWRITER,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "holographic",
    name: "Holographic",
    tagline: "Audiowide. Iridescent chrome. Future-foil.",
    tags: ["dark", "iridescent", "neon"],
    tokens: {
      "--vlc-bg-base": "#0a0014",
      "--vlc-bg-surface": "linear-gradient(135deg,#1a0033 0%,#003d4d 50%,#4d0033 100%)",
      "--vlc-bg-elevated": "linear-gradient(135deg,#2a0050 0%,#005566 50%,#660040 100%)",
      "--vlc-bg-sunken": "#04000a",
      "--vlc-border-subtle": "rgba(180,255,255,0.12)",
      "--vlc-border-normal": "rgba(255,180,255,0.3)",
      "--vlc-accent": "#b6ffff",
      "--vlc-accent-hover": "#80e6e6",
      "--vlc-accent-dim": "rgba(182,255,255,0.18)",
      "--vlc-accent-text": "#ffe0ff",
      "--vlc-seek-played": "linear-gradient(90deg,#b6ffff,#ffe0ff,#fff4b6,#b6ffff)",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#f0f8ff",
      "--vlc-text-secondary": "rgba(240,248,255,0.75)",
      "--vlc-font-ui": AUDIOWIDE,
      "--vlc-radius-sm": "4px",
      "--vlc-radius-md": "8px",
      "--vlc-control-radius": "12px",
    },
    extraCss: "",
  },

  {
    id: "manga-ink",
    name: "Manga Inked",
    tagline: "Bangers. Halftone dots. Comic-panel energy.",
    tags: ["light", "bold", "comic"],
    tokens: {
      "--vlc-bg-base": "#fdfaf2",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#e8e3d6",
      "--vlc-border-subtle": "#000000",
      "--vlc-border-normal": "#000000",
      "--vlc-border-strong": "#000000",
      "--vlc-accent": "#ff2e4c",
      "--vlc-accent-hover": "#cc1a35",
      "--vlc-accent-dim": "rgba(255,46,76,0.16)",
      "--vlc-accent-text": "#000000",
      "--vlc-seek-played": "#000000",
      "--vlc-seek-thumb": "#ff2e4c",
      "--vlc-seek-track": "rgba(0,0,0,0.18)",
      "--vlc-text-primary": "#000000",
      "--vlc-text-secondary": "rgba(0,0,0,0.7)",
      "--vlc-font-ui": BANGERS,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
    },
    extraCss: "",
  },

  {
    id: "mocha-cafe",
    name: "Mocha Café",
    tagline: "Caveat. Handwritten warmth. Latte foam.",
    tags: ["light", "warm", "handwritten"],
    tokens: {
      "--vlc-bg-base": "#f3e8d8",
      "--vlc-bg-surface": "#ede0cc",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#e0d0b8",
      "--vlc-border-subtle": "rgba(80,50,30,0.12)",
      "--vlc-border-normal": "rgba(80,50,30,0.25)",
      "--vlc-accent": "#7c4a2a",
      "--vlc-accent-hover": "#5e3818",
      "--vlc-accent-dim": "rgba(124,74,42,0.14)",
      "--vlc-accent-text": "#7c4a2a",
      "--vlc-seek-played": "#7c4a2a",
      "--vlc-seek-thumb": "#5e3818",
      "--vlc-text-primary": "#3a2414",
      "--vlc-text-secondary": "rgba(58,36,20,0.7)",
      "--vlc-font-ui": CAVEAT,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "14px",
      "--vlc-radius-lg": "22px",
      "--vlc-control-radius": "20px",
      "--vlc-font-size-md": "16px",
      "--vlc-font-size-sm": "14px",
    },
    extraCss: "",
  },

  {
    id: "botanical",
    name: "Botanical",
    tagline: "Fraunces. Deep forest. Eucalyptus accent.",
    tags: ["dark", "green", "serif", "nature"],
    tokens: {
      "--vlc-bg-base": "#0f1d14",
      "--vlc-bg-surface": "#162a1d",
      "--vlc-bg-elevated": "#1f3a28",
      "--vlc-bg-sunken": "#0a140d",
      "--vlc-border-subtle": "rgba(180,220,180,0.08)",
      "--vlc-border-normal": "rgba(180,220,180,0.2)",
      "--vlc-accent": "#a8d5a0",
      "--vlc-accent-hover": "#8ab880",
      "--vlc-accent-dim": "rgba(168,213,160,0.16)",
      "--vlc-accent-text": "#cfeac5",
      "--vlc-seek-played": "#a8d5a0",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e8f0e4",
      "--vlc-text-secondary": "rgba(232,240,228,0.7)",
      "--vlc-font-ui": FRAUNCES,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "12px",
      "--vlc-control-radius": "10px",
    },
    extraCss: "",
  },

  {
    id: "mercury",
    name: "Liquid Mercury",
    tagline: "Syne. Chrome silver. Molten metal.",
    tags: ["dark", "chrome", "metal"],
    tokens: {
      "--vlc-bg-base": "#1a1d22",
      "--vlc-bg-surface": "linear-gradient(180deg,#3a4048 0%,#22262d 100%)",
      "--vlc-bg-elevated": "linear-gradient(180deg,#5a626c 0%,#2a2f37 100%)",
      "--vlc-bg-sunken": "#0e1014",
      "--vlc-border-subtle": "rgba(255,255,255,0.1)",
      "--vlc-border-normal": "rgba(255,255,255,0.22)",
      "--vlc-border-strong": "#c8ccd4",
      "--vlc-accent": "#c8ccd4",
      "--vlc-accent-hover": "#a0a4ac",
      "--vlc-accent-dim": "rgba(200,204,212,0.16)",
      "--vlc-accent-text": "#e8ebf0",
      "--vlc-seek-played": "linear-gradient(90deg,#e8ebf0,#a0a4ac,#e8ebf0)",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e8ebf0",
      "--vlc-text-secondary": "rgba(232,235,240,0.7)",
      "--vlc-font-ui": SYNE,
      "--vlc-radius-sm": "8px",
      "--vlc-radius-md": "14px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "jumbotron",
    name: "Stadium Jumbotron",
    tagline: "Anton. Scoreboard LED. Game-day energy.",
    tags: ["dark", "bold", "sport"],
    tokens: {
      "--vlc-bg-base": "#050505",
      "--vlc-bg-surface": "#0f0f0f",
      "--vlc-bg-elevated": "#1a1a1a",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,200,0,0.18)",
      "--vlc-border-normal": "rgba(255,200,0,0.4)",
      "--vlc-border-strong": "#ffc800",
      "--vlc-accent": "#ff3030",
      "--vlc-accent-hover": "#cc1818",
      "--vlc-accent-dim": "rgba(255,48,48,0.2)",
      "--vlc-accent-text": "#ffc800",
      "--vlc-seek-played": "#ff3030",
      "--vlc-seek-thumb": "#ffc800",
      "--vlc-text-primary": "#ffc800",
      "--vlc-text-secondary": "#ff3030",
      "--vlc-font-ui": ANTON,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
    },
    extraCss: "",
  },
  // ─── Wave 4 — 30 additional heroes. Each is a unique identity: distinct
  // typeface, palette, and chrome treatment. Defensive --vlc-text-primary is
  // always set so the gallery card preview never goes invisible on any
  // active skin, regardless of the active root skin's text color.

  {
    id: "obsidian",
    name: "Obsidian Edge",
    tagline: "DM Serif. Volcanic glass. Hairline gold.",
    tags: ["dark", "serif", "luxury"],
    tokens: {
      "--vlc-bg-base": "#08080a",
      "--vlc-bg-surface": "#101014",
      "--vlc-bg-elevated": "#181820",
      "--vlc-bg-sunken": "#040406",
      "--vlc-border-subtle": "rgba(220,200,160,0.08)",
      "--vlc-border-normal": "rgba(220,200,160,0.22)",
      "--vlc-accent": "#dcc8a0",
      "--vlc-accent-hover": "#c0a878",
      "--vlc-accent-dim": "rgba(220,200,160,0.14)",
      "--vlc-accent-text": "#f0e0c0",
      "--vlc-seek-played": "#dcc8a0",
      "--vlc-seek-thumb": "#f0e0c0",
      "--vlc-text-primary": "#f0e0c0",
      "--vlc-text-secondary": "rgba(240,224,192,0.7)",
      "--vlc-font-ui": DM_SERIF,
      "--vlc-radius-sm": "1px",
      "--vlc-radius-md": "2px",
      "--vlc-control-radius": "1px",
    },
    extraCss: "",
  },

  {
    id: "matrix",
    name: "Matrix Code",
    tagline: "Space Mono. Falling glyphs. Phosphor green rain.",
    tags: ["dark", "mono", "green", "cyber"],
    tokens: {
      "--vlc-bg-base": "#000000",
      "--vlc-bg-surface": "#020a02",
      "--vlc-bg-elevated": "#041504",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(0,255,65,0.18)",
      "--vlc-border-normal": "rgba(0,255,65,0.4)",
      "--vlc-border-strong": "#00ff41",
      "--vlc-accent": "#00ff41",
      "--vlc-accent-hover": "#00cc33",
      "--vlc-accent-dim": "rgba(0,255,65,0.14)",
      "--vlc-accent-text": "#a0ff8a",
      "--vlc-seek-played": "#00ff41",
      "--vlc-seek-thumb": "#a0ff8a",
      "--vlc-text-primary": "#00ff41",
      "--vlc-text-secondary": "rgba(0,255,65,0.7)",
      "--vlc-font-ui": SPACE_MONO,
      "--vlc-font-mono": SPACE_MONO,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "scandi",
    name: "Scandi Light",
    tagline: "Karla. Birch wood. Hygge minimalism.",
    tags: ["light", "minimal", "warm"],
    tokens: {
      "--vlc-bg-base": "#fafaf7",
      "--vlc-bg-surface": "#f2efe8",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#e8e4da",
      "--vlc-border-subtle": "rgba(40,40,40,0.08)",
      "--vlc-border-normal": "rgba(40,40,40,0.16)",
      "--vlc-accent": "#3a6b5c",
      "--vlc-accent-hover": "#284f43",
      "--vlc-accent-dim": "rgba(58,107,92,0.14)",
      "--vlc-accent-text": "#3a6b5c",
      "--vlc-seek-played": "#3a6b5c",
      "--vlc-seek-thumb": "#3a6b5c",
      "--vlc-seek-track": "rgba(40,40,40,0.12)",
      "--vlc-text-primary": "#1a1a1a",
      "--vlc-text-secondary": "rgba(26,26,26,0.65)",
      "--vlc-text-ghost": "rgba(26,26,26,0.42)",
      "--vlc-font-ui": KARLA,
      "--vlc-radius-sm": "4px",
      "--vlc-radius-md": "8px",
      "--vlc-control-radius": "6px",
    },
  },

  {
    id: "bauhaus",
    name: "Bauhaus 1923",
    tagline: "Rubik. Primary blocks. De Stijl geometry.",
    tags: ["light", "bold", "geometric"],
    tokens: {
      "--vlc-bg-base": "#f4f0e5",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#e6dfca",
      "--vlc-border-subtle": "#000000",
      "--vlc-border-normal": "#000000",
      "--vlc-border-strong": "#000000",
      "--vlc-accent": "#d6212f",
      "--vlc-accent-hover": "#a01622",
      "--vlc-accent-dim": "rgba(214,33,47,0.14)",
      "--vlc-accent-text": "#1c47a1",
      "--vlc-seek-played": "#1c47a1",
      "--vlc-seek-thumb": "#f4cc14",
      "--vlc-seek-track": "rgba(0,0,0,0.14)",
      "--vlc-text-primary": "#0a0a0a",
      "--vlc-text-secondary": "rgba(10,10,10,0.7)",
      "--vlc-font-ui": RUBIK,
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "speed-racer",
    name: "Speed Racer",
    tagline: "Righteous. Checker flag. Track-day adrenaline.",
    tags: ["dark", "bold", "sport", "red"],
    tokens: {
      "--vlc-bg-base": "#0a0a0a",
      "--vlc-bg-surface": "#141414",
      "--vlc-bg-elevated": "#1f1f1f",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(255,255,255,0.08)",
      "--vlc-border-normal": "rgba(255,255,255,0.16)",
      "--vlc-accent": "#ff2a2a",
      "--vlc-accent-hover": "#cc1818",
      "--vlc-accent-dim": "rgba(255,42,42,0.2)",
      "--vlc-accent-text": "#ffffff",
      "--vlc-seek-played": "linear-gradient(90deg,#ff2a2a,#ffffff)",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#ffffff",
      "--vlc-text-secondary": "rgba(255,255,255,0.75)",
      "--vlc-font-ui": RIGHTEOUS,
      "--vlc-control-radius": "2px",
    },
    extraCss: "",
  },

  {
    id: "circus",
    name: "Big Top Circus",
    tagline: "Alfa Slab. Carnival stripes. Red & cream.",
    tags: ["light", "bold", "playful"],
    tokens: {
      "--vlc-bg-base": "#fdf6e3",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0e7d0",
      "--vlc-border-subtle": "rgba(140,30,30,0.18)",
      "--vlc-border-normal": "rgba(140,30,30,0.35)",
      "--vlc-border-strong": "#8c1e1e",
      "--vlc-accent": "#c8252c",
      "--vlc-accent-hover": "#9c1a20",
      "--vlc-accent-dim": "rgba(200,37,44,0.14)",
      "--vlc-accent-text": "#8c1e1e",
      "--vlc-seek-played": "#c8252c",
      "--vlc-seek-thumb": "#fdf6e3",
      "--vlc-text-primary": "#3a0a0a",
      "--vlc-text-secondary": "rgba(58,10,10,0.7)",
      "--vlc-font-ui": ALFA_SLAB,
      "--vlc-control-radius": "10px",
      "--vlc-radius-md": "10px",
    },
    extraCss: "",
  },

  {
    id: "rust-belt",
    name: "Rust Belt",
    tagline: "PT Serif. Oxidized steel. Industrial decay.",
    tags: ["dark", "warm", "serif", "vintage"],
    tokens: {
      "--vlc-bg-base": "#1a120c",
      "--vlc-bg-surface": "#241810",
      "--vlc-bg-elevated": "#322218",
      "--vlc-bg-sunken": "#0c0805",
      "--vlc-border-subtle": "rgba(200,90,40,0.16)",
      "--vlc-border-normal": "rgba(200,90,40,0.3)",
      "--vlc-accent": "#c85a28",
      "--vlc-accent-hover": "#9c4218",
      "--vlc-accent-dim": "rgba(200,90,40,0.14)",
      "--vlc-accent-text": "#e89060",
      "--vlc-seek-played": "#c85a28",
      "--vlc-seek-thumb": "#e89060",
      "--vlc-text-primary": "#e8d8c0",
      "--vlc-text-secondary": "rgba(232,216,192,0.7)",
      "--vlc-font-ui": PT_SERIF,
      "--vlc-control-radius": "2px",
    },
  },

  {
    id: "gilded-age",
    name: "Gilded Age",
    tagline: "Cormorant Garamond. Belle Époque cream.",
    tags: ["light", "serif", "luxury"],
    tokens: {
      "--vlc-bg-base": "#f5edd8",
      "--vlc-bg-surface": "#fcf6e2",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#ebe0c2",
      "--vlc-border-subtle": "rgba(120,80,30,0.14)",
      "--vlc-border-normal": "rgba(120,80,30,0.3)",
      "--vlc-border-strong": "#785014",
      "--vlc-accent": "#a07418",
      "--vlc-accent-hover": "#7c5410",
      "--vlc-accent-dim": "rgba(160,116,24,0.14)",
      "--vlc-accent-text": "#785014",
      "--vlc-seek-played": "#a07418",
      "--vlc-seek-thumb": "#785014",
      "--vlc-text-primary": "#2a1e08",
      "--vlc-text-secondary": "rgba(42,30,8,0.7)",
      "--vlc-font-ui": CORMORANT,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "racing-stripes",
    name: "Teko Velocity",
    tagline: "Teko. Italian condensed. Motorsport HUD.",
    tags: ["dark", "bold", "sport"],
    tokens: {
      "--vlc-bg-base": "#0a0e1a",
      "--vlc-bg-surface": "#10172b",
      "--vlc-bg-elevated": "#1c2540",
      "--vlc-bg-sunken": "#05080f",
      "--vlc-border-subtle": "rgba(0,200,120,0.18)",
      "--vlc-border-normal": "rgba(0,200,120,0.4)",
      "--vlc-accent": "#00c878",
      "--vlc-accent-hover": "#00a060",
      "--vlc-accent-dim": "rgba(0,200,120,0.14)",
      "--vlc-accent-text": "#5cf0b0",
      "--vlc-seek-played": "#00c878",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e0fff0",
      "--vlc-text-secondary": "rgba(224,255,240,0.72)",
      "--vlc-font-ui": TEKO,
      "--vlc-control-radius": "2px",
    },
    extraCss: "",
  },

  {
    id: "cyber-deck",
    name: "Cyber Deck",
    tagline: "Chakra Petch. Glitched neon. Edgerunner kit.",
    tags: ["dark", "cyber", "neon", "yellow"],
    tokens: {
      "--vlc-bg-base": "#0e0a14",
      "--vlc-bg-surface": "#1a1224",
      "--vlc-bg-elevated": "#241a32",
      "--vlc-bg-sunken": "#05030a",
      "--vlc-border-subtle": "rgba(255,255,60,0.18)",
      "--vlc-border-normal": "rgba(255,255,60,0.4)",
      "--vlc-border-strong": "#ffff3c",
      "--vlc-accent": "#ffff3c",
      "--vlc-accent-hover": "#cccc20",
      "--vlc-accent-dim": "rgba(255,255,60,0.16)",
      "--vlc-accent-text": "#ffff3c",
      "--vlc-seek-played": "#ffff3c",
      "--vlc-seek-thumb": "#ff00aa",
      "--vlc-text-primary": "#f0e8ff",
      "--vlc-text-secondary": "rgba(240,232,255,0.72)",
      "--vlc-font-ui": CHAKRA,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "kid-show",
    name: "Saturday Cartoon",
    tagline: "Viga. Primary pops. After-school cereal box.",
    tags: ["light", "playful", "kids"],
    tokens: {
      "--vlc-bg-base": "#e8f4ff",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#cce4f8",
      "--vlc-border-subtle": "rgba(0,80,180,0.18)",
      "--vlc-border-normal": "rgba(0,80,180,0.35)",
      "--vlc-border-strong": "#0050b4",
      "--vlc-accent": "#ff7e00",
      "--vlc-accent-hover": "#e06400",
      "--vlc-accent-dim": "rgba(255,126,0,0.16)",
      "--vlc-accent-text": "#0050b4",
      "--vlc-seek-played": "#ff7e00",
      "--vlc-seek-thumb": "#ffe600",
      "--vlc-text-primary": "#0a1a3a",
      "--vlc-text-secondary": "rgba(10,26,58,0.72)",
      "--vlc-font-ui": VIGA,
      "--vlc-radius-sm": "14px",
      "--vlc-radius-md": "22px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "tiki-bar",
    name: "Tiki Bar",
    tagline: "Pacifico. Sunset coral. Pina colada nights.",
    tags: ["light", "playful", "warm"],
    tokens: {
      "--vlc-bg-base": "linear-gradient(180deg,#ffd4a3 0%,#ff8e72 50%,#c84a6e 100%)",
      "--vlc-bg-surface": "rgba(255,255,255,0.65)",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "rgba(60,20,40,0.25)",
      "--vlc-border-subtle": "rgba(60,20,40,0.18)",
      "--vlc-border-normal": "rgba(60,20,40,0.35)",
      "--vlc-accent": "#c84a6e",
      "--vlc-accent-hover": "#a02f54",
      "--vlc-accent-dim": "rgba(200,74,110,0.16)",
      "--vlc-accent-text": "#3c1428",
      "--vlc-seek-played": "#c84a6e",
      "--vlc-seek-thumb": "#fff5dc",
      "--vlc-text-primary": "#3c1428",
      "--vlc-text-secondary": "rgba(60,20,40,0.72)",
      "--vlc-font-ui": PACIFICO,
      "--vlc-radius-sm": "12px",
      "--vlc-radius-md": "20px",
      "--vlc-control-radius": "999px",
    },
    extraCss: "",
  },

  {
    id: "love-letter",
    name: "Love Letter",
    tagline: "Sacramento. Ivory paper. Calligraphic warmth.",
    tags: ["light", "elegant", "handwritten"],
    tokens: {
      "--vlc-bg-base": "#fbf5ec",
      "--vlc-bg-surface": "#fffaf2",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f2ead9",
      "--vlc-border-subtle": "rgba(140,30,80,0.12)",
      "--vlc-border-normal": "rgba(140,30,80,0.26)",
      "--vlc-accent": "#a8345f",
      "--vlc-accent-hover": "#822449",
      "--vlc-accent-dim": "rgba(168,52,95,0.14)",
      "--vlc-accent-text": "#822449",
      "--vlc-seek-played": "#a8345f",
      "--vlc-seek-thumb": "#822449",
      "--vlc-text-primary": "#3a1428",
      "--vlc-text-secondary": "rgba(58,20,40,0.72)",
      "--vlc-font-ui": SACRAMENTO,
      "--vlc-font-size-md": "16px",
      "--vlc-font-size-sm": "14px",
      "--vlc-radius-sm": "4px",
      "--vlc-radius-md": "10px",
      "--vlc-control-radius": "8px",
    },
  },

  {
    id: "notebook",
    name: "Notebook",
    tagline: "Kalam. Ruled lines. Pencil-margin doodles.",
    tags: ["light", "handwritten", "education"],
    tokens: {
      "--vlc-bg-base": "#fdfcf4",
      "--vlc-bg-surface": "#fffef7",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f2efde",
      "--vlc-border-subtle": "rgba(40,60,120,0.16)",
      "--vlc-border-normal": "rgba(40,60,120,0.32)",
      "--vlc-border-strong": "#283c78",
      "--vlc-accent": "#283c78",
      "--vlc-accent-hover": "#1a2a54",
      "--vlc-accent-dim": "rgba(40,60,120,0.14)",
      "--vlc-accent-text": "#283c78",
      "--vlc-seek-played": "#283c78",
      "--vlc-seek-thumb": "#283c78",
      "--vlc-seek-track": "rgba(40,60,120,0.18)",
      "--vlc-text-primary": "#1a1a3a",
      "--vlc-text-secondary": "rgba(26,26,58,0.72)",
      "--vlc-font-ui": KALAM,
    },
    extraCss: "",
  },

  {
    id: "sharpie",
    name: "Sharpie Marker",
    tagline: "Permanent Marker. Hand-lettered protest sign.",
    tags: ["light", "bold", "handwritten"],
    tokens: {
      "--vlc-bg-base": "#fefce8",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0eed0",
      "--vlc-border-subtle": "#000000",
      "--vlc-border-normal": "#000000",
      "--vlc-border-strong": "#000000",
      "--vlc-accent": "#000000",
      "--vlc-accent-hover": "#1a1a1a",
      "--vlc-accent-dim": "rgba(0,0,0,0.12)",
      "--vlc-accent-text": "#000000",
      "--vlc-seek-played": "#000000",
      "--vlc-seek-thumb": "#000000",
      "--vlc-seek-track": "rgba(0,0,0,0.18)",
      "--vlc-text-primary": "#0a0a0a",
      "--vlc-text-secondary": "rgba(10,10,10,0.78)",
      "--vlc-font-ui": PERMANENT,
      "--vlc-radius-sm": "0",
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "neon-tube",
    name: "Monoton Marquee",
    tagline: "Monoton. Vegas marquee bulbs. Tube lighting.",
    tags: ["dark", "neon", "retro"],
    tokens: {
      "--vlc-bg-base": "#0a0014",
      "--vlc-bg-surface": "#160028",
      "--vlc-bg-elevated": "#2a004a",
      "--vlc-bg-sunken": "#03000a",
      "--vlc-border-subtle": "rgba(255,80,180,0.18)",
      "--vlc-border-normal": "rgba(255,80,180,0.4)",
      "--vlc-border-strong": "#ff50b4",
      "--vlc-accent": "#ff50b4",
      "--vlc-accent-hover": "#cc3a8e",
      "--vlc-accent-dim": "rgba(255,80,180,0.18)",
      "--vlc-accent-text": "#ffb4dc",
      "--vlc-seek-played": "#ff50b4",
      "--vlc-seek-thumb": "#fff5b4",
      "--vlc-text-primary": "#ffe8f5",
      "--vlc-text-secondary": "rgba(255,232,245,0.72)",
      "--vlc-font-ui": MONOTON,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "soviet",
    name: "Soviet Poster",
    tagline: "Stalinist. Red constructivism. Heavy slab.",
    tags: ["dark", "bold", "poster", "red"],
    tokens: {
      "--vlc-bg-base": "#1a0a08",
      "--vlc-bg-surface": "#2a1410",
      "--vlc-bg-elevated": "#3a2018",
      "--vlc-bg-sunken": "#0a0403",
      "--vlc-border-subtle": "rgba(240,200,60,0.18)",
      "--vlc-border-normal": "rgba(240,200,60,0.3)",
      "--vlc-border-strong": "#f0c83c",
      "--vlc-accent": "#d8001c",
      "--vlc-accent-hover": "#a40015",
      "--vlc-accent-dim": "rgba(216,0,28,0.2)",
      "--vlc-accent-text": "#f0c83c",
      "--vlc-seek-played": "#d8001c",
      "--vlc-seek-thumb": "#f0c83c",
      "--vlc-text-primary": "#f4e8d0",
      "--vlc-text-secondary": "rgba(244,232,208,0.72)",
      "--vlc-font-ui": STALINIST,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "drag-strip",
    name: "Drag Strip",
    tagline: "Faster One. Hot-rod chrome. NHRA staging lane.",
    tags: ["dark", "bold", "retro", "sport"],
    tokens: {
      "--vlc-bg-base": "#050510",
      "--vlc-bg-surface": "#0a0a1c",
      "--vlc-bg-elevated": "#14142c",
      "--vlc-bg-sunken": "#02020a",
      "--vlc-border-subtle": "rgba(255,140,0,0.18)",
      "--vlc-border-normal": "rgba(255,140,0,0.36)",
      "--vlc-border-strong": "#ff8c00",
      "--vlc-accent": "#ff8c00",
      "--vlc-accent-hover": "#cc6f00",
      "--vlc-accent-dim": "rgba(255,140,0,0.16)",
      "--vlc-accent-text": "#ffc880",
      "--vlc-seek-played": "linear-gradient(90deg,#ff8c00,#ffe000)",
      "--vlc-seek-thumb": "#ffe000",
      "--vlc-text-primary": "#fff5e0",
      "--vlc-text-secondary": "rgba(255,245,224,0.72)",
      "--vlc-font-ui": FASTER_ONE,
      "--vlc-control-radius": "0",
    },
  },

  {
    id: "gothic",
    name: "Gothic Cathedral",
    tagline: "UnifrakturCook. Vaulted blackletter. Stained glass.",
    tags: ["dark", "serif", "historic"],
    tokens: {
      "--vlc-bg-base": "#0a0810",
      "--vlc-bg-surface": "#14101c",
      "--vlc-bg-elevated": "#1f1830",
      "--vlc-bg-sunken": "#050408",
      "--vlc-border-subtle": "rgba(180,80,200,0.16)",
      "--vlc-border-normal": "rgba(180,80,200,0.32)",
      "--vlc-border-strong": "#b450c8",
      "--vlc-accent": "#b450c8",
      "--vlc-accent-hover": "#8c3aa0",
      "--vlc-accent-dim": "rgba(180,80,200,0.14)",
      "--vlc-accent-text": "#d890e8",
      "--vlc-seek-played": "linear-gradient(90deg,#b450c8,#d890e8,#b450c8)",
      "--vlc-seek-thumb": "#d890e8",
      "--vlc-text-primary": "#e8d0f0",
      "--vlc-text-secondary": "rgba(232,208,240,0.72)",
      "--vlc-font-ui": UNIFRAKTUR,
      "--vlc-control-radius": "2px",
    },
  },

  {
    id: "slab-press",
    name: "Slab Press",
    tagline: "Zilla Slab. Editorial weight. Mozilla heritage.",
    tags: ["light", "serif", "editorial"],
    tokens: {
      "--vlc-bg-base": "#fdfaf2",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f0ebde",
      "--vlc-border-subtle": "rgba(20,20,20,0.1)",
      "--vlc-border-normal": "rgba(20,20,20,0.22)",
      "--vlc-border-strong": "#141414",
      "--vlc-accent": "#0060df",
      "--vlc-accent-hover": "#0046a8",
      "--vlc-accent-dim": "rgba(0,96,223,0.14)",
      "--vlc-accent-text": "#0060df",
      "--vlc-seek-played": "#0060df",
      "--vlc-seek-thumb": "#141414",
      "--vlc-text-primary": "#141414",
      "--vlc-text-secondary": "rgba(20,20,20,0.7)",
      "--vlc-font-ui": ZILLA,
      "--vlc-radius-sm": "2px",
      "--vlc-control-radius": "4px",
    },
  },

  {
    id: "abril-fashion",
    name: "Vogue Editorial",
    tagline: "Abril Fatface. High-fashion masthead. Crème.",
    tags: ["light", "serif", "fashion"],
    tokens: {
      "--vlc-bg-base": "#fbf7f1",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#ece4d6",
      "--vlc-border-subtle": "rgba(0,0,0,0.08)",
      "--vlc-border-normal": "rgba(0,0,0,0.2)",
      "--vlc-border-strong": "#000000",
      "--vlc-accent": "#000000",
      "--vlc-accent-hover": "#222222",
      "--vlc-accent-dim": "rgba(0,0,0,0.08)",
      "--vlc-accent-text": "#000000",
      "--vlc-seek-played": "#000000",
      "--vlc-seek-thumb": "#000000",
      "--vlc-text-primary": "#0a0a0a",
      "--vlc-text-secondary": "rgba(10,10,10,0.7)",
      "--vlc-font-ui": ABRIL,
      "--vlc-radius-sm": "0",
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "exo-future",
    name: "Exo Future",
    tagline: "Exo 2. Soft sci-fi. Cobalt twilight.",
    tags: ["dark", "scifi", "blue"],
    tokens: {
      "--vlc-bg-base": "#0a1428",
      "--vlc-bg-surface": "#0f1d3a",
      "--vlc-bg-elevated": "#182a52",
      "--vlc-bg-sunken": "#050a14",
      "--vlc-border-subtle": "rgba(120,200,255,0.16)",
      "--vlc-border-normal": "rgba(120,200,255,0.32)",
      "--vlc-accent": "#3d9bff",
      "--vlc-accent-hover": "#1a78dc",
      "--vlc-accent-dim": "rgba(61,155,255,0.16)",
      "--vlc-accent-text": "#80c0ff",
      "--vlc-seek-played": "#3d9bff",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#e0eeff",
      "--vlc-text-secondary": "rgba(224,238,255,0.72)",
      "--vlc-font-ui": EXO,
      "--vlc-radius-sm": "6px",
      "--vlc-control-radius": "10px",
    },
  },

  {
    id: "noir",
    name: "Film Noir",
    tagline: "Courier Prime. Smoky shadow. 1940s detective.",
    tags: ["dark", "mono", "cinema"],
    tokens: {
      "--vlc-bg-base": "#0a0a0a",
      "--vlc-bg-surface": "#141414",
      "--vlc-bg-elevated": "#1c1c1c",
      "--vlc-bg-sunken": "#000000",
      "--vlc-border-subtle": "rgba(200,180,140,0.14)",
      "--vlc-border-normal": "rgba(200,180,140,0.28)",
      "--vlc-accent": "#c8b48c",
      "--vlc-accent-hover": "#a89870",
      "--vlc-accent-dim": "rgba(200,180,140,0.14)",
      "--vlc-accent-text": "#e0ccaa",
      "--vlc-seek-played": "#c8b48c",
      "--vlc-seek-thumb": "#e0ccaa",
      "--vlc-text-primary": "#e0ccaa",
      "--vlc-text-secondary": "rgba(224,204,170,0.72)",
      "--vlc-font-ui": COURIER_PRIME,
      "--vlc-font-mono": COURIER_PRIME,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "share-tech",
    name: "Mainframe Op",
    tagline: "Share Tech Mono. Punch-card pragmatism.",
    tags: ["dark", "mono", "retro"],
    tokens: {
      "--vlc-bg-base": "#0a0c12",
      "--vlc-bg-surface": "#141822",
      "--vlc-bg-elevated": "#1e2434",
      "--vlc-bg-sunken": "#040608",
      "--vlc-border-subtle": "rgba(255,200,120,0.14)",
      "--vlc-border-normal": "rgba(255,200,120,0.28)",
      "--vlc-accent": "#ffaa3c",
      "--vlc-accent-hover": "#cc8628",
      "--vlc-accent-dim": "rgba(255,170,60,0.14)",
      "--vlc-accent-text": "#ffd28a",
      "--vlc-seek-played": "#ffaa3c",
      "--vlc-seek-thumb": "#ffd28a",
      "--vlc-text-primary": "#f4ead4",
      "--vlc-text-secondary": "rgba(244,234,212,0.72)",
      "--vlc-font-ui": SHARE_TECH,
      "--vlc-font-mono": SHARE_TECH,
      "--vlc-control-radius": "0",
    },
  },

  {
    id: "pirate",
    name: "Black Sails",
    tagline: "Pirata One. Weathered parchment. Skull & crossbones.",
    tags: ["dark", "serif", "vintage"],
    tokens: {
      "--vlc-bg-base": "#0c0a08",
      "--vlc-bg-surface": "#16120c",
      "--vlc-bg-elevated": "#241d12",
      "--vlc-bg-sunken": "#050403",
      "--vlc-border-subtle": "rgba(220,180,100,0.14)",
      "--vlc-border-normal": "rgba(220,180,100,0.3)",
      "--vlc-border-strong": "#dcb464",
      "--vlc-accent": "#dcb464",
      "--vlc-accent-hover": "#b08a40",
      "--vlc-accent-dim": "rgba(220,180,100,0.14)",
      "--vlc-accent-text": "#f0d088",
      "--vlc-seek-played": "#dcb464",
      "--vlc-seek-thumb": "#f0d088",
      "--vlc-text-primary": "#ecd9a4",
      "--vlc-text-secondary": "rgba(236,217,164,0.72)",
      "--vlc-font-ui": PIRATA,
      "--vlc-control-radius": "0",
    },
  },

  {
    id: "atomic-cafe",
    name: "Atomic Diner",
    tagline: "Gruppo. Jet-age boomerang. Formica mint.",
    tags: ["light", "retro", "playful"],
    tokens: {
      "--vlc-bg-base": "#dff4ec",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#bce0d2",
      "--vlc-border-subtle": "rgba(0,80,72,0.16)",
      "--vlc-border-normal": "rgba(0,80,72,0.32)",
      "--vlc-border-strong": "#005048",
      "--vlc-accent": "#ff4f7c",
      "--vlc-accent-hover": "#cc3a5e",
      "--vlc-accent-dim": "rgba(255,79,124,0.16)",
      "--vlc-accent-text": "#005048",
      "--vlc-seek-played": "#ff4f7c",
      "--vlc-seek-thumb": "#005048",
      "--vlc-text-primary": "#003028",
      "--vlc-text-secondary": "rgba(0,48,40,0.72)",
      "--vlc-font-ui": GRUPPO,
      "--vlc-radius-sm": "10px",
      "--vlc-radius-md": "18px",
      "--vlc-control-radius": "999px",
    },
  },

  {
    id: "nixie",
    name: "Nixie Tube",
    tagline: "Nixie One. Glowing decatron numerals. Brass.",
    tags: ["dark", "mono", "vintage"],
    tokens: {
      "--vlc-bg-base": "#0a0604",
      "--vlc-bg-surface": "#160e08",
      "--vlc-bg-elevated": "#24180c",
      "--vlc-bg-sunken": "#040302",
      "--vlc-border-subtle": "rgba(255,140,60,0.16)",
      "--vlc-border-normal": "rgba(255,140,60,0.32)",
      "--vlc-accent": "#ff8c3c",
      "--vlc-accent-hover": "#cc6e24",
      "--vlc-accent-dim": "rgba(255,140,60,0.14)",
      "--vlc-accent-text": "#ffb480",
      "--vlc-seek-played": "#ff8c3c",
      "--vlc-seek-thumb": "#ffb480",
      "--vlc-text-primary": "#ffb480",
      "--vlc-text-secondary": "rgba(255,180,128,0.72)",
      "--vlc-font-ui": NIXIE,
      "--vlc-font-mono": NIXIE,
      "--vlc-control-radius": "0",
    },
    extraCss: "",
  },

  {
    id: "marshmallow",
    name: "Marshmallow",
    tagline: "Comfortaa. Pillow-soft pastels. Cloud nine.",
    tags: ["light", "soft", "minimal"],
    tokens: {
      "--vlc-bg-base": "#fef6f9",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#f4e6ee",
      "--vlc-border-subtle": "rgba(180,140,160,0.16)",
      "--vlc-border-normal": "rgba(180,140,160,0.28)",
      "--vlc-accent": "#d490b0",
      "--vlc-accent-hover": "#b06c8c",
      "--vlc-accent-dim": "rgba(212,144,176,0.14)",
      "--vlc-accent-text": "#a05880",
      "--vlc-seek-played": "#d490b0",
      "--vlc-seek-thumb": "#ffffff",
      "--vlc-text-primary": "#4a283a",
      "--vlc-text-secondary": "rgba(74,40,58,0.7)",
      "--vlc-font-ui": COMFORTAA,
      "--vlc-radius-sm": "16px",
      "--vlc-radius-md": "24px",
      "--vlc-radius-lg": "32px",
      "--vlc-control-radius": "999px",
    },
  },

  {
    id: "low-rise",
    name: "Low-Rise SaaS",
    tagline: "ABeeZee. Calm gray-blue. Quiet dashboard.",
    tags: ["light", "minimal", "pro"],
    tokens: {
      "--vlc-bg-base": "#f7f8fa",
      "--vlc-bg-surface": "#ffffff",
      "--vlc-bg-elevated": "#ffffff",
      "--vlc-bg-sunken": "#eef0f4",
      "--vlc-border-subtle": "rgba(30,40,60,0.08)",
      "--vlc-border-normal": "rgba(30,40,60,0.16)",
      "--vlc-accent": "#4f5bdc",
      "--vlc-accent-hover": "#3a45b0",
      "--vlc-accent-dim": "rgba(79,91,220,0.12)",
      "--vlc-accent-text": "#4f5bdc",
      "--vlc-seek-played": "#4f5bdc",
      "--vlc-seek-thumb": "#4f5bdc",
      "--vlc-text-primary": "#0f1530",
      "--vlc-text-secondary": "rgba(15,21,48,0.65)",
      "--vlc-font-ui": ABEEZEE,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "10px",
      "--vlc-control-radius": "8px",
    },
  },

  {
    id: "silkscreen",
    name: "Silkscreen",
    tagline: "Silkscreen. Tiny pixel grid. Indie console.",
    tags: ["dark", "pixel", "retro"],
    tokens: {
      "--vlc-bg-base": "#0e0e0e",
      "--vlc-bg-surface": "#181818",
      "--vlc-bg-elevated": "#242424",
      "--vlc-bg-sunken": "#040404",
      "--vlc-border-subtle": "#3c3c3c",
      "--vlc-border-normal": "#5c5c5c",
      "--vlc-border-strong": "#9c9c9c",
      "--vlc-accent": "#3cff7d",
      "--vlc-accent-hover": "#28cc60",
      "--vlc-accent-dim": "rgba(60,255,125,0.16)",
      "--vlc-accent-text": "#3cff7d",
      "--vlc-seek-played": "#3cff7d",
      "--vlc-seek-thumb": "#3cff7d",
      "--vlc-text-primary": "#e8e8e8",
      "--vlc-text-secondary": "rgba(232,232,232,0.7)",
      "--vlc-font-ui": SILKSCREEN,
      "--vlc-font-mono": SILKSCREEN,
      "--vlc-control-radius": "0",
      "--vlc-radius-sm": "0",
      "--vlc-radius-md": "0",
      "--vlc-font-size-sm": "10px",
      "--vlc-font-size-md": "11px",
    },
    extraCss: "",
  },
];


export const HEROES_BY_ID: Record<string, SkinHero> = Object.fromEntries(
  HEROES.map((h) => [h.id, h]),
);
