// Premium ("Pro") skins. Curated singletons — NOT fanned out across the
// accent palette in registry.ts, so each renders as a single hand-tuned
// card pinned to the top of the gallery. Every token set here is designed
// to clear WCAG-AA against bg-base / bg-surface / bg-sunken intrinsically;
// the contrast normalizer should never need to rescue these.

import type { SkinHero } from "./types";

const SF = '"Inter", "SF Pro Text", system-ui, -apple-system, sans-serif';
const SF_DISPLAY = '"Inter Tight", "SF Pro Display", system-ui, sans-serif';
const MONO = '"JetBrains Mono", ui-monospace, SFMono-Regular, monospace';

export const PREMIUM_HEROES: SkinHero[] = [
  // 1 — Obsidian Pro. Matte black, electric cyan, hairline chrome.
  {
    id: "obsidian-pro",
    name: "Obsidian Pro",
    tagline: "Matte black. Electric cyan. Hairline chrome.",
    tier: "premium",
    tags: ["premium", "dark", "minimal", "cyan", "pro"],
    tokens: {
      "--vlc-bg-base": "#0A0A0C",
      "--vlc-bg-surface": "#141418",
      "--vlc-bg-elevated": "#1C1C22",
      "--vlc-bg-sunken": "#050506",
      "--vlc-bg-raised": "#1C1C22",
      "--vlc-border-subtle": "rgba(255,255,255,0.06)",
      "--vlc-border-normal": "rgba(255,255,255,0.12)",
      "--vlc-border-strong": "rgba(255,255,255,0.22)",
      "--vlc-text-primary": "#F5F7FA",
      "--vlc-text-secondary": "rgba(245,247,250,0.82)",
      "--vlc-text-ghost": "rgba(245,247,250,0.62)",
      "--vlc-accent": "#22D3EE",
      "--vlc-accent-hover": "#67E8F9",
      "--vlc-accent-dim": "rgba(34,211,238,0.18)",
      "--vlc-accent-text": "#67E8F9",
      "--vlc-seek-played": "#22D3EE",
      "--vlc-seek-thumb": "#ECFEFF",
      "--vlc-seek-buffered": "rgba(255,255,255,0.22)",
      "--vlc-seek-track": "rgba(255,255,255,0.08)",
      "--vlc-font-ui": SF,
      "--vlc-font-display": SF_DISPLAY,
      "--vlc-font-mono": MONO,
      "--vlc-radius-sm": "6px",
      "--vlc-radius-md": "10px",
      "--vlc-radius-lg": "14px",
      "--vlc-shadow-popup":
        "0 1px 0 rgba(255,255,255,0.06) inset, 0 18px 48px -12px rgba(0,0,0,0.7), 0 4px 16px -6px rgba(0,0,0,0.5)",
    },
    extraCss: "",
  },

  // 2 — Aurora Glass. Iridescent gradient base, frosted chrome.
  {
    id: "aurora-glass",
    name: "Aurora Glass",
    tagline: "Iridescent gradient. Frosted glass. Syne display.",
    tier: "premium",
    tags: ["premium", "dark", "glass", "gradient", "pro"],
    tokens: {
      "--vlc-bg-base":
        "linear-gradient(135deg, #0B0F1F 0%, #1A1340 45%, #2A1450 100%)",
      "--vlc-bg-surface": "rgba(28, 26, 56, 0.78)",
      "--vlc-bg-elevated": "rgba(40, 36, 78, 0.82)",
      "--vlc-bg-sunken": "#080820",
      "--vlc-bg-raised": "rgba(40, 36, 78, 0.82)",
      "--vlc-border-subtle": "rgba(167,139,250,0.18)",
      "--vlc-border-normal": "rgba(167,139,250,0.32)",
      "--vlc-border-strong": "rgba(167,139,250,0.50)",
      "--vlc-text-primary": "#F4F2FF",
      "--vlc-text-secondary": "rgba(244,242,255,0.82)",
      "--vlc-text-ghost": "rgba(244,242,255,0.62)",
      "--vlc-accent": "#A78BFA",
      "--vlc-accent-hover": "#C4B5FD",
      "--vlc-accent-dim": "rgba(167,139,250,0.22)",
      "--vlc-accent-text": "#C4B5FD",
      "--vlc-seek-played":
        "linear-gradient(90deg, #A78BFA 0%, #67E8F9 100%)",
      "--vlc-seek-thumb": "#F0EAFF",
      "--vlc-seek-buffered": "rgba(199,210,254,0.30)",
      "--vlc-seek-track": "rgba(255,255,255,0.10)",
      "--vlc-font-ui": '"Manrope", system-ui, sans-serif',
      "--vlc-font-display": '"Syne", "Manrope", system-ui, sans-serif',
      "--vlc-font-mono": MONO,
      "--vlc-radius-sm": "8px",
      "--vlc-radius-md": "14px",
      "--vlc-radius-lg": "20px",
    },
    extraCss: "",
  },

  // 3 — Editorial Noir. Premium LIGHT skin. Paper + ink + copper.
  {
    id: "editorial-noir",
    name: "Editorial Noir",
    tagline: "Paper and ink. Cormorant display. Copper accent.",
    tier: "premium",
    tags: ["premium", "light", "serif", "editorial", "pro"],
    tokens: {
      "--vlc-bg-base": "#F5F3EE",
      "--vlc-bg-surface": "#FFFFFF",
      "--vlc-bg-elevated": "#FAF8F3",
      "--vlc-bg-sunken": "#ECE9E1",
      "--vlc-bg-raised": "#FAF8F3",
      "--vlc-border-subtle": "rgba(13,13,13,0.08)",
      "--vlc-border-normal": "rgba(13,13,13,0.16)",
      "--vlc-border-strong": "rgba(13,13,13,0.32)",
      "--vlc-text-primary": "#0D0D0D",
      "--vlc-text-secondary": "rgba(13,13,13,0.72)",
      "--vlc-text-ghost": "rgba(13,13,13,0.52)",
      "--vlc-accent": "#8A6A1F",
      "--vlc-accent-hover": "#6E5418",
      "--vlc-accent-dim": "rgba(138,106,31,0.16)",
      "--vlc-accent-text": "#6E5418",
      "--vlc-seek-played": "#8A6A1F",
      "--vlc-seek-thumb": "#0D0D0D",
      "--vlc-seek-buffered": "rgba(13,13,13,0.22)",
      "--vlc-seek-track": "rgba(13,13,13,0.10)",
      "--vlc-control-hover": "rgba(13,13,13,0.06)",
      "--vlc-font-ui": '"IBM Plex Sans", "Inter", system-ui, sans-serif',
      "--vlc-font-display": '"Cormorant Garamond", "Instrument Serif", Georgia, serif',
      "--vlc-font-mono": MONO,
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "4px",
      "--vlc-radius-lg": "6px",
    },
    extraCss: "",
  },

  // 4 — Velocity HUD. Cinematic teal cockpit + amber HUD.
  {
    id: "velocity-hud",
    name: "Velocity HUD",
    tagline: "Cockpit teal. Amber HUD. Rajdhani caps.",
    tier: "premium",
    tags: ["premium", "dark", "hud", "amber", "pro"],
    tokens: {
      "--vlc-bg-base": "#031A24",
      "--vlc-bg-surface": "#062231",
      "--vlc-bg-elevated": "#082B3E",
      "--vlc-bg-sunken": "#011018",
      "--vlc-bg-raised": "#082B3E",
      "--vlc-border-subtle": "rgba(255,138,61,0.14)",
      "--vlc-border-normal": "rgba(255,138,61,0.30)",
      "--vlc-border-strong": "rgba(255,138,61,0.55)",
      "--vlc-text-primary": "#F2FAFF",
      "--vlc-text-secondary": "rgba(242,250,255,0.82)",
      "--vlc-text-ghost": "rgba(242,250,255,0.62)",
      "--vlc-accent": "#FF8A3D",
      "--vlc-accent-hover": "#FFA866",
      "--vlc-accent-dim": "rgba(255,138,61,0.20)",
      "--vlc-accent-text": "#FFB987",
      "--vlc-seek-played": "#FF8A3D",
      "--vlc-seek-thumb": "#FFE3CC",
      "--vlc-seek-buffered": "rgba(255,255,255,0.22)",
      "--vlc-seek-track": "rgba(255,255,255,0.08)",
      "--vlc-font-ui": '"Rajdhani", "Inter", system-ui, sans-serif',
      "--vlc-font-display": '"Rajdhani", "Inter", system-ui, sans-serif',
      "--vlc-font-mono": MONO,
      "--vlc-radius-sm": "2px",
      "--vlc-radius-md": "4px",
      "--vlc-radius-lg": "6px",
    },
    extraCss: "",
  },

  // 5 — Linen Couture. Premium LIGHT skin. Warm sand + terracotta.
  {
    id: "linen-couture",
    name: "Linen Couture",
    tagline: "Warm sand. Terracotta. Instrument Serif.",
    tier: "premium",
    tags: ["premium", "light", "warm", "serif", "pro"],
    tokens: {
      "--vlc-bg-base": "#F7F3EC",
      "--vlc-bg-surface": "#FFFDF7",
      "--vlc-bg-elevated": "#FBF6EC",
      "--vlc-bg-sunken": "#EAE3D4",
      "--vlc-bg-raised": "#FBF6EC",
      "--vlc-border-subtle": "rgba(26,26,26,0.08)",
      "--vlc-border-normal": "rgba(26,26,26,0.18)",
      "--vlc-border-strong": "rgba(26,26,26,0.36)",
      "--vlc-text-primary": "#1A1A1A",
      "--vlc-text-secondary": "rgba(26,26,26,0.72)",
      "--vlc-text-ghost": "rgba(26,26,26,0.52)",
      "--vlc-accent": "#9C3F22",
      "--vlc-accent-hover": "#7C311A",
      "--vlc-accent-dim": "rgba(156,63,34,0.16)",
      "--vlc-accent-text": "#7C311A",
      "--vlc-seek-played": "#9C3F22",
      "--vlc-seek-thumb": "#1A1A1A",
      "--vlc-seek-buffered": "rgba(26,26,26,0.22)",
      "--vlc-seek-track": "rgba(26,26,26,0.10)",
      "--vlc-control-hover": "rgba(26,26,26,0.06)",
      "--vlc-font-ui": '"Inter", system-ui, sans-serif',
      "--vlc-font-display": '"Instrument Serif", "Cormorant Garamond", Georgia, serif',
      "--vlc-font-mono": MONO,
      "--vlc-radius-sm": "10px",
      "--vlc-radius-md": "14px",
      "--vlc-radius-lg": "20px",
    },
    extraCss: "",
  },
];
